#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate
python manage.py compilemessages
python manage.py collectstatic --noinput


# Initialize cache 
python manage.py init_cache 
# Start Django server on public IP interface, port 8000
python manage.py runserver 0.0.0.0:8000 
