#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
#python manage.py runserver_plus 0.0.0.0:8000
#daphne -b 0.0.0.0 -p 8001 mpcd.asgi:corpus
#daphne config.asgi:application --b 0.0.0.0
uvicorn config.asgi:application --host 0.0.0.0 --reload