# Generated by Django 4.1 on 2022-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldictionary',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dictionary', 'verbose_name_plural': 'historical dictionarys'},
        ),
        migrations.AlterModelOptions(
            name='historicallemma',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical lemma', 'verbose_name_plural': 'historical lemmas'},
        ),
        migrations.AlterModelOptions(
            name='historicalmeaning',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical meaning', 'verbose_name_plural': 'historical meanings'},
        ),
        migrations.AlterModelOptions(
            name='historicalsemantic',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical semantic', 'verbose_name_plural': 'historical semantics'},
        ),
        migrations.AlterModelOptions(
            name='historicaltermtech',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical term tech', 'verbose_name_plural': 'historical term techs'},
        ),
        migrations.AlterField(
            model_name='historicaldictionary',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallemma',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmeaning',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsemantic',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltermtech',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
