# Generated by Django 3.1.13 on 2021-09-08 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition', models.CharField(blank=True, max_length=350, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='definition',
            field=models.ManyToManyField(to='dict.Definition'),
        ),
    ]
