# Generated by Django 3.1.13 on 2022-03-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalentry',
            name='_order',
        ),
        migrations.AlterOrderWithRespectTo(
            name='entry',
            order_with_respect_to=None,
        ),
    ]
