# Generated by Django 3.1.13 on 2021-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldictionary',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
