# Generated by Django 3.1.13 on 2021-08-30 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dict',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dict.dictionary'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='doi',
            field=models.URLField(blank=True, null=True),
        ),
    ]
