# Generated by Django 3.1.13 on 2022-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(fields=('definition', 'language'), name='definition_language'),
        ),
    ]
