# Generated by Django 3.1.13 on 2022-02-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_entry_related_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltranslation',
            old_name='meaning',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='meaning',
            new_name='text',
        ),
    ]
