# Generated by Django 3.1.13 on 2021-10-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20211001_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalentry',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanword',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.lang'),
        ),
        migrations.AlterField(
            model_name='loanword',
            name='translation',
            field=models.ManyToManyField(blank=True, to='dict.Translation'),
        ),
    ]
