# Generated by Django 3.1.13 on 2021-09-29 06:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20210914_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lang',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
