# Generated by Django 3.1.13 on 2022-03-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20220310_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['lemma__word']},
        ),
    ]
