# Generated by Django 3.1.13 on 2021-09-02 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_historicaldictionary_historicalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeaningEnglish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('meaning', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='meaning_en',
            field=models.ManyToManyField(to='dict.MeaningEnglish'),
        ),
    ]
