# Generated by Django 3.1.13 on 2022-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20220325_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionary',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='dictionary',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='dictionary_name_slug'),
        ),
    ]
