# Generated by Django 3.1.13 on 2022-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20220530_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallemma',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
