# Generated by Django 3.1.13 on 2022-07-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0017_auto_20220711_1112'),
        ('dict', '0003_auto_20220530_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Definition',
        ),
        migrations.AlterField(
            model_name='historicallemma',
            name='comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.comment'),
        ),
        migrations.AlterField(
            model_name='historicalmeaning',
            name='comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.comment'),
        ),
        migrations.AlterField(
            model_name='historicalsemantic',
            name='comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.comment'),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.comment'),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.comment'),
        ),
        migrations.AlterField(
            model_name='semantic',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.comment'),
        ),
        migrations.DeleteModel(
            name='HistoricalDefinition',
        ),
    ]
