# Generated by Django 3.1.13 on 2021-09-08 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0003_auto_20210908_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalMeaning',
            new_name='HistoricalTranslation',
        ),
        migrations.RenameModel(
            old_name='Meaning',
            new_name='Translation',
        ),
        migrations.AlterModelOptions(
            name='historicaltranslation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical translation'},
        ),
        migrations.AddField(
            model_name='lemma',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.lang'),
        ),
    ]
