# Generated by Django 3.1.13 on 2021-10-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20211001_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
