# Generated by Django 3.1.13 on 2022-03-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20220325_1230'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('reference', 'url'), name='reference_url'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(fields=('language', 'text'), name='translation_language_text'),
        ),
    ]
