# Generated by Django 3.1.13 on 2021-10-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_auto_20211001_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='cross_reference',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='literature',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='loanword',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='historicalentry',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='historicalentry',
            name='loanword',
        ),
    ]
