# Generated by Django 3.1.13 on 2021-09-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_auto_20210929_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lang',
            old_name='temp_id',
            new_name='id',
        ),
    ]
