# Generated by Django 3.1.13 on 2022-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_auto_20220325_1249'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('dict', 'lemma'), name='entry_dict_lemma'),
        ),
    ]
