# Generated by Django 3.1.13 on 2021-09-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_auto_20210908_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.lang'),
        ),
        migrations.AlterField(
            model_name='lang',
            name='language',
            field=models.CharField(choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('grc', 'Ancient Greek (to 1453)'), ('pal', 'Pahlavi'), ('xpr', 'Parthian')], max_length=3, unique=True),
        ),
    ]
