# Generated by Django 3.1.13 on 2021-10-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_auto_20211001_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='slug',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
