# Generated by Django 3.1.13 on 2021-09-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_auto_20210929_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='language',
            field=models.CharField(choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, unique=True),
        ),
    ]
