# Generated by Django 4.0.6 on 2022-07-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_alter_lemma_related_lemmas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='related_lemmas',
            field=models.ManyToManyField(blank=True, to='dict.lemma'),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='related_meanings',
            field=models.ManyToManyField(blank=True, to='dict.meaning'),
        ),
        migrations.AlterField(
            model_name='semantic',
            name='related_semantics',
            field=models.ManyToManyField(blank=True, to='dict.semantic'),
        ),
    ]
