# Generated by Django 3.1.13 on 2022-03-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_auto_20220328_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldefinition',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicallemma',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalloanword',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='loanword',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
    ]
