# Generated by Django 3.1.13 on 2021-09-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_auto_20210929_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='loanword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dict.loanword'),
        ),
    ]
