# Generated by Django 3.1.13 on 2021-10-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_auto_20211001_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanword',
            name='language',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.lang'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.lang'),
        ),
    ]
