# Generated by Django 3.1.13 on 2022-04-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_auto_20220331_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranslation',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
