# Generated by Django 3.1.13 on 2021-10-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_auto_20211002_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dict',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dict.dictionary'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.lang'),
        ),
    ]
