# Generated by Django 3.1.13 on 2022-04-29 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0007_auto_20220426_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='HistoricalCategory',
            new_name='HistoricalTermTech',
        ),
        migrations.AlterModelOptions(
            name='historicaltermtech',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical term tech'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='translations',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='TermTech',
        ),
        migrations.CreateModel(
            name='Semantic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('meanings', models.ManyToManyField(blank=True, related_name='semantic_meanings', to='dict.Meaning')),
                ('term_techs', models.ManyToManyField(blank=True, related_name='semantic_term_tech', to='dict.TermTech')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSemantic',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical semantic',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeaning',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical meaning',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='entry',
            name='semantics',
            field=models.ManyToManyField(blank=True, related_name='entry_semantics', to='dict.Semantic'),
        ),
    ]
