# Generated by Django 3.1.13 on 2021-10-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_auto_20211002_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='loanword',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
    ]
