# Generated by Django 3.1.13 on 2022-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_auto_20220429_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meaning',
            options={'ordering': ['meaning']},
        ),
        migrations.AlterField(
            model_name='semantic',
            name='term_techs',
            field=models.ManyToManyField(blank=True, related_name='semantic_term_techs', to='dict.TermTech'),
        ),
        migrations.AddConstraint(
            model_name='meaning',
            constraint=models.UniqueConstraint(fields=('meaning', 'language'), name='meaning_language_meaning'),
        ),
    ]
