# Generated by Django 3.1.13 on 2022-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_auto_20220505_1217'),
        ('dict', '0009_auto_20220503_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalentry',
            name='dict',
        ),
        migrations.RemoveField(
            model_name='historicalentry',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalentry',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='historicalloanword',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='loanword',
            name='translations',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='source_languages',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicaldictionary',
            name='source_languages',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('ara', 'Arabic'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('guj', 'Gujarati'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('san', 'Sanskrit'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicallemma',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lemma',
            name='related_lemmas',
            field=models.ManyToManyField(blank=True, related_name='_lemma_related_lemmas_+', to='dict.Lemma'),
        ),
        migrations.AddField(
            model_name='meaning',
            name='related_meanings',
            field=models.ManyToManyField(blank=True, related_name='_meaning_related_meanings_+', to='dict.Meaning'),
        ),
        migrations.AddField(
            model_name='semantic',
            name='lemmas',
            field=models.ManyToManyField(blank=True, related_name='semantic_lemmas', to='dict.Lemma'),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='HistoricalEntry',
        ),
        migrations.DeleteModel(
            name='HistoricalLoanWord',
        ),
        migrations.DeleteModel(
            name='LoanWord',
        ),
    ]
