# Generated by Django 3.1.13 on 2022-05-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0010_auto_20220505_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltranslation',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.DeleteModel(
            name='HistoricalTranslation',
        ),
    ]
