# Generated by Django 3.1.13 on 2022-05-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0011_auto_20220505_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeaning',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
