# Generated by Django 3.1.13 on 2021-10-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0012_auto_20211004_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='definition',
            new_name='definitions',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='loanword',
            new_name='loanwords',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='literature',
            new_name='references',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='translation',
            new_name='translations',
        ),
        migrations.RenameField(
            model_name='historicalentry',
            old_name='loanword',
            new_name='loanwords',
        ),
        migrations.RenameField(
            model_name='loanword',
            old_name='translation',
            new_name='translations',
        ),
    ]
