# Generated by Django 3.1.13 on 2022-05-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0012_auto_20220505_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='related_meanings',
            field=models.ManyToManyField(blank=True, related_name='lemma_related_meanings', to='dict.Meaning'),
        ),
    ]
