# Generated by Django 3.1.13 on 2022-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0013_lemma_related_meanings'),
    ]

    operations = [
        migrations.AddField(
            model_name='semantic',
            name='related_semantics',
            field=models.ManyToManyField(blank=True, related_name='_semantic_related_semantics_+', to='dict.Semantic'),
        ),
    ]
