# Generated by Django 3.1.13 on 2021-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0014_auto_20211004_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='loanwords',
            field=models.ManyToManyField(blank=True, to='dict.LoanWord'),
        ),
    ]
