# Generated by Django 3.1.13 on 2021-10-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0015_auto_20211004_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('astr', 'astronomy'), ('bot', 'botany'), ('econom', 'economy'), ('geogr', 'geography'), ('legal', 'legal'), ('measure', 'measurement'), ('med', 'medicine'), ('myth', 'mythology'), ('philos', 'philosophy'), ('pol', 'politics'), ('purity', 'purity'), ('ritual', 'ritual'), ('theol', 'theology'), ('zool', 'zoology')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='meaning',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference',
            field=models.CharField(blank=True, max_length=350, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='meaning',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
