# Generated by Django 3.1.13 on 2021-10-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0016_auto_20211005_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('lemma',)},
        ),
    ]
