# Generated by Django 3.1.13 on 2021-10-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0017_auto_20211006_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
