# Generated by Django 3.1.13 on 2021-10-06 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0018_auto_20211006_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dict',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary', to='dict.dictionary'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lemma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='dict.word'),
        ),
    ]
