# Generated by Django 3.1.13 on 2021-10-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0019_auto_20211006_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='encat', to='dict.Category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='definitions',
            field=models.ManyToManyField(blank=True, related_name='endef', to='dict.Definition'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='dict',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='endict', to='dict.dictionary'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lemma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enlemma', to='dict.word'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='loanwords',
            field=models.ManyToManyField(blank=True, related_name='enloan', to='dict.LoanWord'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='enref', to='dict.Reference'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='entrans', to='dict.Translation'),
        ),
    ]
