# Generated by Django 3.1.13 on 2021-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0020_auto_20211006_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanword',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='loantrans', to='dict.Translation'),
        ),
    ]
