# Generated by Django 3.1.13 on 2021-10-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0021_auto_20211006_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='lemma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dict.word'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='loanwords',
            field=models.ManyToManyField(blank=True, to='dict.LoanWord'),
        ),
    ]
