# Generated by Django 3.1.13 on 2021-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0025_auto_20211007_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanword',
            name='translations',
            field=models.ManyToManyField(blank=True, to='dict.Translation'),
        ),
    ]
