# Generated by Django 3.1.13 on 2022-01-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0026_auto_20211007_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='lemma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_entry', to='dict.word'),
        ),
    ]
