# Generated by Django 3.1.13 on 2022-01-26 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0027_auto_20220103_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('category', models.CharField(choices=[('astr', 'astronomy'), ('bot', 'botany'), ('econom', 'economy'), ('geogr', 'geography'), ('legal', 'legal'), ('measure', 'measurement'), ('med', 'medicine'), ('myth', 'mythology'), ('philos', 'philosophy'), ('pol', 'politics'), ('purity', 'purity'), ('ritual', 'ritual'), ('theol', 'theology'), ('zool', 'zoology')], db_index=True, max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDefinition',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('definition', models.TextField(blank=True, db_index=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical definition',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLoanWord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('word', models.CharField(db_index=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical loan word',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('word', models.CharField(db_index=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical word',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, unique=True)),
                ('history', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Lang',
        ),
        migrations.AlterField(
            model_name='entry',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='entry_categories', to='dict.Category'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='definitions',
            field=models.ManyToManyField(blank=True, related_name='entry_definitions', to='dict.Definition'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='dict',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_dict', to='dict.dictionary'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='lemma',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_lemma', to='dict.word'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='loanwords',
            field=models.ManyToManyField(blank=True, related_name='entry_loanwords', to='dict.LoanWord'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='entry_references', to='dict.Reference'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='entry_translations', to='dict.Translation'),
        ),
        migrations.AlterField(
            model_name='loanword',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='loanword_translations', to='dict.Translation'),
        ),
        migrations.AddField(
            model_name='historicalword',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.language'),
        ),
        migrations.AddField(
            model_name='historicalloanword',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.language'),
        ),
        migrations.AddField(
            model_name='historicaldefinition',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.language'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definition_language', to='dict.language'),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.language'),
        ),
        migrations.AlterField(
            model_name='loanword',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanword_language', to='dict.language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_language', to='dict.language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_language', to='dict.language'),
        ),
    ]
