# Generated by Django 3.1.13 on 2022-01-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0028_auto_20220126_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='identifier',
        ),
    ]
