# Generated by Django 3.1.13 on 2022-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0030_auto_20220126_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallemma',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='lemma',
            constraint=models.UniqueConstraint(fields=('word', 'language'), name='word_language'),
        ),
    ]
