version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
<<<<<<< HEAD
=======
  local_elastic_data: {}
  local_redis_data: {}
>>>>>>> dev

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: treeflow_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - ../corpora/texts_exports:/app_data:ro
      - .:/app_output
      - ../users:/user_data:ro
      
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: treeflow_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: treeflow_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: treeflow_local_django
    container_name: celery_worker
    depends_on:
      - django
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: celery -A treeflow worker --loglevel=info
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local  # or treeflow.settings.production

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: treeflow_local_django
    container_name: celery_beat
    depends_on:
      - django
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: celery -A treeflow beat --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local  # or treeflow.settings.production
      - CELERY_BEAT=true
