version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_redis_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: treeflow_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - ../corpora/texts_exports:/app_data:ro
      - .:/app_output
      - ../users:/user_data:ro
      
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  node:
    image: node:latest
    container_name: node_tailwind_builder
    depends_on:
      - django
    working_dir: /app/theme/static_src # Make sure this path matches your local structure
    volumes:
      - .:/app:z 
    command: /bin/sh -c "npm install && npm run dev"
    tty: true 
    
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: treeflow_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: "redis:latest"
    container_name: redis
    volumes:
      - local_redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: treeflow_local_django
    container_name: celery_worker
    depends_on:
      - django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: celery -A config.celery_app worker -l info

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: treeflow_local_django
    container_name: celery_beat
    depends_on:
      - django
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: celery -A config.celery_app beat -l info
