#!/usr/bin/env bash


### Create a database backup.
###
### Usage:
###     $ docker-compose -f <environment>.yml (exec |run --rm) postgres backdown


set -o errexit
set -o pipefail
set -o nounset


working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"


while sleep "${BACKUP_DELAY_TIME}"; do
  find "${BACKUP_DIR_PATH}" -mtime "+${BACKUP_RETENTION_DAYS}" -delete
  backup
done
