# Generated by Django 3.1.13 on 2021-09-30 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dict', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BibEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Codex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('library', models.CharField(blank=True, max_length=100)),
                ('signature', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CodexSentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodexText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, choices=[('UNT', 'untouched'), ('IPR', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head', models.PositiveSmallIntegerField()),
                ('rel', models.CharField(choices=[('acl', 'clausal modifier of noun (adnominal clause)'), ('advcl', 'adverbial clause modifier'), ('advmod', 'adverbial modifier'), ('amod', 'adjectival modifier'), ('appos', 'appositional modifier'), ('aux', 'auxiliary'), ('case', 'case marking'), ('cc', 'coordinating conjunction'), ('ccomp', 'clausal complement'), ('compound', 'compound'), ('conj', 'conjunct'), ('cop', 'copula'), ('det', 'determiner'), ('discourse', 'discourse element'), ('fixed', 'fixed multiword expression'), ('iobj', 'indirect object'), ('mark', 'marker'), ('nmod', 'nominal modifier'), ('nsubj', 'nominal subject'), ('nummod', 'numeric modifier'), ('obj', 'object'), ('obl', 'oblique nominal'), ('root', 'root')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditionSentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditionText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, choices=[('UNT', 'untouched'), ('IPR', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MorphologicalAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(choices=[('ADJ', 'ADJ'), ('ADP', 'ADP'), ('ADV', 'ADV'), ('AUX', 'AUX'), ('CCONJ', 'CCONJ'), ('DET', 'DET'), ('INTJ', 'INTJ'), ('NOUN', 'NOUN'), ('NUM', 'NUM'), ('PART', 'PART'), ('PRON', 'PRON'), ('PROPN', 'PROPN'), ('PUNCT', 'PUNCT'), ('SCONJO', 'SCONJO'), ('SYM', 'SYM'), ('VERB', 'VERB'), ('X', 'X')], max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project', models.TextField(blank=True)),
                ('reference', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyntacticAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextSigle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigle', models.CharField(choices=[('AM', 'AM'), ('AOD', 'AŌD'), ('Aog', 'Aog'), ('ASS', 'ASS'), ('AWM', 'AWM'), ('AWN', 'AWN'), ('AZ', 'AZ'), ('CHP', 'CHP'), ('DA', 'DA'), ('Dd', 'Dd'), ('Dk3', 'Dk3'), ('Dk4', 'Dk4'), ('Dk5', 'Dk5'), ('Dk6', 'Dk6'), ('Dk7', 'Dk7'), ('Dk8', 'Dk8'), ('Dk9', 'Dk9'), ('DkC', 'DkC'), ('DMX', 'DMX'), ('ENN', 'ENN'), ('GA', 'GA'), ('GBd', 'GBd'), ('Her', 'Hēr'), ('HKR', 'HKR'), ('HN', 'HN'), ('IndBd', 'IndBd'), ('KAP', 'KAP'), ('MFRH', 'MFRH'), ('MHD', 'MHD'), ('MK_Andarz', 'MK-Andarz'), ('MYFr', 'MYFr'), ('N', 'N'), ('NM', 'NM'), ('OHD', 'OHD'), ('P', 'P'), ('PahlRivDd', 'PahlRivDd'), ('PT', 'PT'), ('PV', 'PV'), ('PY', 'PY'), ('RAF', 'RAF'), ('REA', 'RĒA'), ('SGW', 'ŠGW'), ('SiE', 'ŠiĒ'), ('SnS', 'ŠnŠ'), ('Vr', 'Vr'), ('Vyt', 'Vyt'), ('WCNA', 'WCNA'), ('WD', 'WD'), ('WDWM', 'WDWM'), ('WZ', 'WZ'), ('XD', 'X&D'), ('XAv', 'XAv'), ('ZFJ', 'ZFJ'), ('ZWY', 'ZWY')], max_length=10, unique=True)),
                ('genre', models.CharField(choices=[('ZAN', 'zand'), ('PTE', 'PT-epitomes'), ('PTR', 'PT-reworking'), ('TEO', 'theological'), ('AUT', 'authorial-th'), ('JUR', 'jur'), ('AND', 'andarz'), ('NAR', 'narrative')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcription', models.CharField(max_length=50)),
                ('transliteration', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('avestan', models.URLField(blank=True, max_length=100, null=True)),
                ('features', models.ManyToManyField(blank=True, to='corpus.MorphologicalAnnotation')),
                ('lemma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.entry')),
                ('pos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.pos')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_token', to='corpus.token')),
                ('syntax_annotations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.syntacticannotation')),
            ],
        ),
        migrations.CreateModel(
            name='CodexToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='corpus.token')),
                ('position', models.PositiveSmallIntegerField(null=True)),
            ],
            bases=('corpus.token',),
        ),
         migrations.CreateModel(
            name='HistoricalCodex',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('library', models.CharField(blank=True, max_length=100)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical codex',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCodexSentence',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical codex sentence',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCodexText',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, choices=[('UNT', 'untouched'), ('IPR', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical codex text',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCodexToken',
            fields=[
                ('token_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='corpus.token')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('transcription', models.CharField(max_length=50)),
                ('transliteration', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('avestan', models.URLField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveSmallIntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical codex token',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEdition',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical edition',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEditionSentence',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical edition sentence',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEditionText',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, choices=[('UNT', 'untouched'), ('IPR', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical edition text',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFolio',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical folio',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLine',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('number', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical line',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalToken',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('transcription', models.CharField(max_length=50)),
                ('transliteration', models.CharField(blank=True, max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('avestan', models.URLField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical token',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='textsigle',
            constraint=models.CheckConstraint(check=models.Q(sigle__in=['AM', 'AOD', 'Aog', 'ASS', 'AWM', 'AWN', 'AZ', 'CHP', 'DA', 'Dd', 'Dk3', 'Dk4', 'Dk5', 'Dk6', 'Dk7', 'Dk8', 'Dk9', 'DkC', 'DMX', 'ENN', 'GA', 'GBd', 'Her', 'HKR', 'HN', 'IndBd', 'KAP', 'MFRH', 'MHD', 'MK_Andarz', 'MYFr', 'N', 'NM', 'OHD', 'P', 'PahlRivDd', 'PT', 'PV', 'PY', 'RAF', 'REA', 'SGW', 'SiE', 'SnS', 'Vr', 'Vyt', 'WCNA', 'WD', 'WDWM', 'WZ', 'XD', 'XAv', 'ZFJ', 'ZWY']), name='valid_sigle'),
        ),
        migrations.AddConstraint(
            model_name='textsigle',
            constraint=models.CheckConstraint(check=models.Q(genre__in=['ZAN', 'PTE', 'PTR', 'TEO', 'AUT', 'JUR', 'AND', 'NAR']), name='valid_genre'),
        ),
        migrations.AddConstraint(
            model_name='textsigle',
            constraint=models.UniqueConstraint(fields=('sigle', 'genre'), name='sigle_genre'),
        ),
        migrations.AddField(
            model_name='syntacticannotation',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.dependency'),
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.author'),
        ),
        migrations.AddConstraint(
            model_name='pos',
            constraint=models.CheckConstraint(check=models.Q(pos__in=['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJO', 'SYM', 'VERB', 'X']), name='valid_pos'),
        ),
        migrations.AddField(
            model_name='morphologicalannotation',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.feature'),
        ),
        migrations.AddField(
            model_name='morphologicalannotation',
            name='feature_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.featurevalue'),
        ),
        migrations.AddField(
            model_name='line',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='lemma',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.entry'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='pos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.pos'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='syntax_annotations',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.syntacticannotation'),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='side',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='codex',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codex'),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleditiontext',
            name='edition',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.edition'),
        ),
        migrations.AddField(
            model_name='historicaleditiontext',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.author'),
        ),
        migrations.AddField(
            model_name='historicaleditiontext',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleditiontext',
            name='resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.resource'),
        ),
        migrations.AddField(
            model_name='historicaleditiontext',
            name='text_sigle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='historicaleditionsentence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleditionsentence',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.editiontext'),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcodextoken',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcodextoken',
            name='lemma',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.entry'),
        ),
        migrations.AddField(
            model_name='historicalcodextoken',
            name='line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='historicalcodextoken',
            name='pos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.pos'),
        ),
        migrations.AddField(
            model_name='historicalcodextoken',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='historicalcodextoken',
            name='syntax_annotations',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.syntacticannotation'),
        ),
        migrations.AddField(
            model_name='historicalcodextext',
            name='codex',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codex'),
        ),
        migrations.AddField(
            model_name='historicalcodextext',
            name='editor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.author'),
        ),
        migrations.AddField(
            model_name='historicalcodextext',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcodextext',
            name='resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.resource'),
        ),
        migrations.AddField(
            model_name='historicalcodextext',
            name='text_sigle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='historicalcodexsentence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcodexsentence',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codextext'),
        ),
        migrations.AddField(
            model_name='historicalcodex',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcodex',
            name='scribe',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.author'),
        ),
        migrations.AddField(
            model_name='folio',
            name='codex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.codex'),
        ),
        migrations.AddField(
            model_name='editiontext',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator_edition', to='corpus.Author'),
        ),
        migrations.AddField(
            model_name='editiontext',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.edition'),
        ),
        migrations.AddField(
            model_name='editiontext',
            name='editor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_edition', to='corpus.author'),
        ),
        migrations.AddField(
            model_name='editiontext',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.resource'),
        ),
        migrations.AddField(
            model_name='editiontext',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='editionsentence',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.editiontext'),
        ),
        migrations.AddField(
            model_name='editionsentence',
            name='tokens',
            field=models.ManyToManyField(to='corpus.Token'),
        ),
        migrations.AddField(
            model_name='edition',
            name='author',
            field=models.ManyToManyField(blank=True, to='corpus.Author'),
        ),
        migrations.AddField(
            model_name='edition',
            name='references',
            field=models.ManyToManyField(blank=True, to='corpus.BibEntry'),
        ),
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.CheckConstraint(check=models.Q(rel__in=['acl', 'advcl', 'advmod', 'amod', 'appos', 'aux', 'case', 'cc', 'ccomp', 'compound', 'conj', 'cop', 'det', 'discourse', 'fixed', 'iobj', 'mark', 'nmod', 'nsubj', 'nummod', 'obj', 'obl', 'root']), name='valid_rel'),
        ),
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.UniqueConstraint(fields=('head', 'rel'), name='head_rel'),
        ),
        migrations.AddField(
            model_name='codextext',
            name='codex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.codex'),
        ),
        migrations.AddField(
            model_name='codextext',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='collaborator_codex', to='corpus.Author'),
        ),
        migrations.AddField(
            model_name='codextext',
            name='editor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_codex', to='corpus.author'),
        ),
        migrations.AddField(
            model_name='codextext',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.resource'),
        ),
        migrations.AddField(
            model_name='codextext',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='codexsentence',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.codextext'),
        ),
        migrations.AddField(
            model_name='codex',
            name='facsimile',
            field=models.ManyToManyField(blank=True, to='corpus.BibEntry'),
        ),
        migrations.AddField(
            model_name='codex',
            name='scribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.author'),
        ),
        migrations.AddField(
            model_name='bibentry',
            name='authors',
            field=models.ManyToManyField(to='corpus.Author'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('name', 'last_name'), name='name_lastname'),
        ),
        migrations.AddConstraint(
            model_name='morphologicalannotation',
            constraint=models.UniqueConstraint(fields=('feature', 'feature_value'), name='feature_featurevalue'),
        ),
        migrations.AddConstraint(
            model_name='editiontext',
            constraint=models.CheckConstraint(check=models.Q(stage__in=['UNT', 'IPR', 'FIN']), name='valid_stage_edition'),
        ),
        migrations.AddField(
            model_name='codextoken',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.line'),
        ),
        migrations.AddConstraint(
            model_name='codextext',
            constraint=models.CheckConstraint(check=models.Q(stage__in=['UNT', 'IPR', 'FIN']), name='valid_stage_codex'),
        ),
        migrations.AddField(
            model_name='codexsentence',
            name='tokens',
            field=models.ManyToManyField(to='corpus.CodexToken'),
        ),
    ]
