# Generated by Django 4.1.4 on 2023-01-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibentry',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbibentry',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
