# Generated by Django 3.1.13 on 2022-01-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pos',
            old_name='pos',
            new_name='identifier',
        ),
    ]
