# Generated by Django 3.1.13 on 2021-09-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codex',
            name='facsimile',
            field=models.ManyToManyField(blank=True, to='corpus.BibEntry'),
        ),
        migrations.AlterField(
            model_name='codex',
            name='library',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='codex',
            name='scribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.author'),
        ),
        migrations.AlterField(
            model_name='codex',
            name='signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcodex',
            name='library',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcodex',
            name='signature',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
