# Generated by Django 4.0.6 on 2022-07-20 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0001_initial'),
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='lemmas',
            field=models.ManyToManyField(blank=True, related_name='token_lemmas', to='dict.lemma'),
        ),
        migrations.AddField(
            model_name='token',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_line', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='token',
            name='meanings',
            field=models.ManyToManyField(blank=True, related_name='token_meanings', to='dict.meaning'),
        ),
        migrations.AddField(
            model_name='token',
            name='morphological_annotation',
            field=models.ManyToManyField(blank=True, related_name='token_morphological_annotation', to='corpus.morphologicalannotation'),
        ),
        migrations.AddField(
            model_name='token',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='token',
            name='syntactic_annotation',
            field=models.ManyToManyField(blank=True, related_name='token_syntactic_annotation', to='corpus.dependency'),
        ),
        migrations.AddField(
            model_name='token',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_text', to='corpus.text'),
        ),
        migrations.AddConstraint(
            model_name='textsigle',
            constraint=models.UniqueConstraint(fields=('sigle', 'genre'), name='sigle_genre'),
        ),
        migrations.AddField(
            model_name='text',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='text_collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_corpus', to='corpus.corpus'),
        ),
        migrations.AddField(
            model_name='text',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='text_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='text_resources', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='text',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='text_sources', to='corpus.source'),
        ),
        migrations.AddField(
            model_name='text',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_text_sigle', to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='source',
            name='bib_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_bib_entry', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='sentence_comments', to='corpus.comment'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='corpus.sentence'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentence_text', to='corpus.text'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='tokens',
            field=models.ManyToManyField(related_name='sentence_tokens', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='translations',
            field=models.ManyToManyField(related_name='sentence_translations', to='dict.meaning'),
        ),
        migrations.AddField(
            model_name='section',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.comment'),
        ),
        migrations.AddField(
            model_name='section',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_container', to='corpus.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='corpus.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_section_type', to='corpus.sectiontype'),
        ),
        migrations.AddField(
            model_name='section',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_source', to='corpus.source'),
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_text', to='corpus.text'),
        ),
        migrations.AddField(
            model_name='section',
            name='tokens',
            field=models.ManyToManyField(related_name='section_tokens', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='resource',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='resource_authors', to='corpus.author'),
        ),
        migrations.AddConstraint(
            model_name='morphologicalannotation',
            constraint=models.UniqueConstraint(fields=('feature', 'feature_value'), name='feature_featurevalue'),
        ),
        migrations.AddField(
            model_name='line',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='line_comments', to='corpus.comment'),
        ),
        migrations.AddField(
            model_name='line',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_folio', to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='line',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.text'),
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='corpus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.corpus'),
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='text_sigle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='bib_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.sentence'),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.text'),
        ),
        migrations.AddField(
            model_name='historicalsectiontype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.comment'),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='container',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.section'),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.section'),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='section_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.sectiontype'),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.source'),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.text'),
        ),
        migrations.AddField(
            model_name='historicalmorphologicalannotation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='folio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='facsimile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.facsimile'),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='historicalfacsimile',
            name='bib_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='historicalfacsimile',
            name='codex_part',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codexpart'),
        ),
        migrations.AddField(
            model_name='historicalfacsimile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='bib_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldependency',
            name='head',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='historicaldependency',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcorpus',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcodexpart',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcodex',
            name='bib_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='historicalcodex',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbibentry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folio',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='folio_comments', to='corpus.comment'),
        ),
        migrations.AddField(
            model_name='folio',
            name='facsimile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folio_facsimile', to='corpus.facsimile'),
        ),
        migrations.AddField(
            model_name='folio',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='facsimile',
            name='bib_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facsimile_reference', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='facsimile',
            name='codex_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facsimile_codex_part', to='corpus.codexpart'),
        ),
        migrations.AddField(
            model_name='facsimile',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='facsimile_comments', to='corpus.comment'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='dependency_comments', to='corpus.comment'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependency_head', to='corpus.token'),
        ),
        migrations.AddConstraint(
            model_name='corpus',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='corpus_name_slug'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codexpart',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='codex_part_comments', to='corpus.comment'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('name', 'last_name'), name='name_lastname'),
        ),
        migrations.AddField(
            model_name='token',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='token_comments', to='corpus.tokencomment'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('corpus', 'title'), name='corpus_title'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(fields=('number', 'text'), name='sentence_number_text'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('number', 'folio'), name='number_folio'),
        ),
        migrations.AddField(
            model_name='historicalcodexpart',
            name='codex',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codex'),
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(fields=('identifier', 'facsimile', 'number'), name='identifier_facsimile_number'),
        ),
        migrations.AddField(
            model_name='edition',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='edition_references', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='edition',
            name='text_sigles',
            field=models.ManyToManyField(blank=True, related_name='edition_text_sigles', to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='codexpart',
            name='codex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_part_codex', to='corpus.codex'),
        ),
        migrations.AddField(
            model_name='codex',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='codex_comments', to='corpus.comment'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('number', 'text'), name='token_number_text'),
        ),
    ]
