# Generated by Django 3.1.13 on 2022-03-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(fields=('number', 'text'), name='number_text'),
        ),
    ]
