# Generated by Django 3.1.13 on 2022-06-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmorphologicalannotation',
            name='feature',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmorphologicalannotation',
            name='feature_value',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature_value',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
