# Generated by Django 3.1.13 on 2021-12-08 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCorpus',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical corpus',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSentence',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('translation', models.TextField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sentence',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalText',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, choices=[('UNT', 'untouched'), ('PRO', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('corpus', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.corpus')),
                ('editor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.author')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical text',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('translation', models.TextField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(blank=True, choices=[('UNT', 'untouched'), ('PRO', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3)),
                ('codex_source', models.ManyToManyField(blank=True, null=True, to='corpus.Codex')),
                ('collaborator', models.ManyToManyField(blank=True, related_name='collaborator_text', to='corpus.Author')),
                ('corpus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.corpus')),
                ('edition_source', models.ManyToManyField(blank=True, null=True, to='corpus.Edition')),
                ('editor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_text', to='corpus.author')),
            ],
        ),
        migrations.RemoveField(
            model_name='codextext',
            name='codex',
        ),
        migrations.RemoveField(
            model_name='codextext',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='codextext',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='codextext',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='codextext',
            name='text_sigle',
        ),
        migrations.RemoveField(
            model_name='editionsentence',
            name='text',
        ),
        migrations.RemoveField(
            model_name='editionsentence',
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='editiontext',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='editiontext',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='editiontext',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='editiontext',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='editiontext',
            name='text_sigle',
        ),
        migrations.RemoveField(
            model_name='historicalcodexsentence',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcodexsentence',
            name='text',
        ),
        migrations.RemoveField(
            model_name='historicalcodextext',
            name='codex',
        ),
        migrations.RemoveField(
            model_name='historicalcodextext',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='historicalcodextext',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcodextext',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='historicalcodextext',
            name='text_sigle',
        ),
        migrations.RemoveField(
            model_name='historicaleditionsentence',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaleditionsentence',
            name='text',
        ),
        migrations.RemoveField(
            model_name='historicaleditiontext',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='historicaleditiontext',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='historicaleditiontext',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaleditiontext',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='historicaleditiontext',
            name='text_sigle',
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='CodexSentence',
        ),
        migrations.DeleteModel(
            name='CodexText',
        ),
        migrations.DeleteModel(
            name='EditionSentence',
        ),
        migrations.DeleteModel(
            name='EditionText',
        ),
        migrations.DeleteModel(
            name='HistoricalCodexSentence',
        ),
        migrations.DeleteModel(
            name='HistoricalCodexText',
        ),
        migrations.DeleteModel(
            name='HistoricalEditionSentence',
        ),
        migrations.DeleteModel(
            name='HistoricalEditionText',
        ),
        migrations.AddField(
            model_name='text',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.resource'),
        ),
        migrations.AddField(
            model_name='text',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.text'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='tokens',
            field=models.ManyToManyField(to='corpus.Token'),
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='resource',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.resource'),
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='text_sigle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='historicalsentence',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.text'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.CheckConstraint(check=models.Q(stage__in=['UNT', 'PRO', 'FIN']), name='valid_stage'),
        ),
    ]
