# Generated by Django 3.1.13 on 2022-01-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codex',
            name='copy_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcodex',
            name='copy_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
