# Generated by Django 3.1.13 on 2022-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20220106_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codex',
            name='sigle',
            field=models.CharField(choices=[('MK', 'MK'), ('TD1', 'TD1'), ('TD4a', 'TD4a'), ('DH6', 'DH6'), ('BK', 'BK'), ('TD2', 'TD2'), ('MJ', 'Minocher Jamaspji62(Dd)'), ('IOL', 'IOL CCXXVIII (PRDd)'), ('B', 'B'), ('P', 'P'), ('M51', 'M51'), ('K20', 'K20'), ('K20b', 'K20b'), ('K27', 'K27'), ('K35', 'K35'), ('K43a', 'K43a'), ('K43b', 'K43b'), ('K26', 'K26'), ('msMHD', 'MS of MHD')], default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcodex',
            name='sigle',
            field=models.CharField(choices=[('MK', 'MK'), ('TD1', 'TD1'), ('TD4a', 'TD4a'), ('DH6', 'DH6'), ('BK', 'BK'), ('TD2', 'TD2'), ('MJ', 'Minocher Jamaspji62(Dd)'), ('IOL', 'IOL CCXXVIII (PRDd)'), ('B', 'B'), ('P', 'P'), ('M51', 'M51'), ('K20', 'K20'), ('K20b', 'K20b'), ('K27', 'K27'), ('K35', 'K35'), ('K43a', 'K43a'), ('K43b', 'K43b'), ('K26', 'K26'), ('msMHD', 'MS of MHD')], db_index=True, default='', max_length=10),
        ),
    ]
