# Generated by Django 3.1.13 on 2022-01-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20220113_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folio',
            old_name='name',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='historicalfolio',
            old_name='name',
            new_name='identifier',
        ),
    ]
