# Generated by Django 3.1.13 on 2022-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20220603_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmorphologicalannotation',
            name='feature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmorphologicalannotation',
            name='feature_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
