# Generated by Django 4.1 on 2022-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbibentry',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bib entry', 'verbose_name_plural': 'historical bib entrys'},
        ),
        migrations.AlterModelOptions(
            name='historicalcodex',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical codex', 'verbose_name_plural': 'historical codexs'},
        ),
        migrations.AlterModelOptions(
            name='historicalcodexpart',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical codex part', 'verbose_name_plural': 'historical codex parts'},
        ),
        migrations.AlterModelOptions(
            name='historicalcomment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical comment', 'verbose_name_plural': 'historical comments'},
        ),
        migrations.AlterModelOptions(
            name='historicalcorpus',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical corpus', 'verbose_name_plural': 'historical corpuss'},
        ),
        migrations.AlterModelOptions(
            name='historicaldependency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dependency', 'verbose_name_plural': 'historical dependencys'},
        ),
        migrations.AlterModelOptions(
            name='historicaledition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical edition', 'verbose_name_plural': 'historical editions'},
        ),
        migrations.AlterModelOptions(
            name='historicalfacsimile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical facsimile', 'verbose_name_plural': 'historical facsimiles'},
        ),
        migrations.AlterModelOptions(
            name='historicalfolio',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical folio', 'verbose_name_plural': 'historical folios'},
        ),
        migrations.AlterModelOptions(
            name='historicalline',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical line', 'verbose_name_plural': 'historical lines'},
        ),
        migrations.AlterModelOptions(
            name='historicalmorphologicalannotation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical morphological annotation', 'verbose_name_plural': 'historical morphological annotations'},
        ),
        migrations.AlterModelOptions(
            name='historicalsection',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical section', 'verbose_name_plural': 'historical sections'},
        ),
        migrations.AlterModelOptions(
            name='historicalsectiontype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical section type', 'verbose_name_plural': 'historical section types'},
        ),
        migrations.AlterModelOptions(
            name='historicalsentence',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sentence', 'verbose_name_plural': 'historical sentences'},
        ),
        migrations.AlterModelOptions(
            name='historicalsource',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical source', 'verbose_name_plural': 'historical sources'},
        ),
        migrations.AlterModelOptions(
            name='historicaltext',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical text', 'verbose_name_plural': 'historical texts'},
        ),
        migrations.AlterModelOptions(
            name='historicaltoken',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical token', 'verbose_name_plural': 'historical tokens'},
        ),
        migrations.AlterField(
            model_name='historicalbibentry',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcodex',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcodexpart',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcorpus',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldependency',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfacsimile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfolio',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalline',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalmorphologicalannotation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsection',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsectiontype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsentence',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsource',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltext',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
