# Generated by Django 3.1.13 on 2022-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20220325_1141'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('corpus', 'title'), name='corpus_title'),
        ),
    ]
