# Generated by Django 3.1.13 on 2021-12-13 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20211208_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltext',
            name='description',
        ),
        migrations.RemoveField(
            model_name='text',
            name='description',
        ),
        migrations.AddField(
            model_name='edition',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.textsigle'),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='text_sigle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.textsigle'),
        ),
    ]
