# Generated by Django 3.1.13 on 2021-09-17 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20210917_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcodextoken',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.token'),
        ),
        migrations.AddField(
            model_name='token',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_token', to='corpus.token'),
        ),
        migrations.AlterField(
            model_name='codextext',
            name='stage',
            field=models.CharField(blank=True, choices=[('UNT', 'untouched'), ('IPR', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3),
        ),
        migrations.AlterField(
            model_name='editiontext',
            name='stage',
            field=models.CharField(blank=True, choices=[('UNT', 'untouched'), ('IPR', 'in_progress'), ('FIN', 'finished')], default='UNT', max_length=3),
        ),
    ]
