# Generated by Django 3.1.13 on 2022-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20220607_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsigle',
            name='genre',
            field=models.CharField(choices=[('ZAN', 'zand'), ('PTE', 'PT-epitomes'), ('PTR', 'PT-reworking'), ('TEO', 'theological'), ('AUT', 'authorial-th'), ('JUR', 'jur'), ('AND', 'andarz'), ('NAR', 'narrative')], max_length=3),
        ),
        migrations.AlterField(
            model_name='textsigle',
            name='sigle',
            field=models.CharField(choices=[('AM', 'AM'), ('AOD', 'AŌD'), ('Aog', 'Aog'), ('ASS', 'ASS'), ('AWM', 'AWM'), ('AWN', 'AWN'), ('AZ', 'AZ'), ('CHP', 'CHP'), ('DA', 'DA'), ('Dd', 'Dd'), ('Dk3', 'Dk3'), ('Dk4', 'Dk4'), ('Dk5', 'Dk5'), ('Dk6', 'Dk6'), ('Dk7', 'Dk7'), ('Dk8', 'Dk8'), ('Dk9', 'Dk9'), ('DkC', 'DkC'), ('DMX', 'DMX'), ('ENN', 'ENN'), ('GA', 'GA'), ('GBd', 'GBd'), ('Her', 'Hēr'), ('HKR', 'HKR'), ('HN', 'HN'), ('IndBd', 'IndBd'), ('KAP', 'KAP'), ('MFRH', 'MFRH'), ('MHD', 'MHD'), ('MK_Andarz', 'MK-Andarz'), ('MYFr', 'MYFr'), ('N', 'N'), ('NM', 'NM'), ('OHD', 'OHD'), ('P', 'P'), ('PahlRivDd', 'PahlRivDd'), ('PT', 'PT'), ('PV', 'PV'), ('PY', 'PY'), ('RAF', 'RAF'), ('REA', 'RĒA'), ('SGW', 'ŠGW'), ('SiE', 'ŠiĒ'), ('SnS', 'ŠnŠ'), ('Vr', 'Vr'), ('Vyt', 'Vyt'), ('WCNA', 'WCNA'), ('WD', 'WD'), ('WDWM', 'WDWM'), ('WZ', 'WZ'), ('XD', 'X&D'), ('XAv', 'XAv'), ('ZFJ', 'ZFJ'), ('ZWY', 'ZWY')], max_length=10),
        ),
    ]
