# Generated by Django 3.1.13 on 2022-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20220519_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltoken',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='pos',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='pos',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
