# Generated by Django 3.1.13 on 2022-01-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20220106_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcodex',
            name='scribe',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='scribe',
        ),
        migrations.AddField(
            model_name='codex',
            name='scribe',
            field=models.ManyToManyField(blank=True, null=True, to='corpus.Author'),
        ),
    ]
