# Generated by Django 3.1.13 on 2021-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20211213_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='codex_source',
            field=models.ManyToManyField(blank=True, to='corpus.Codex'),
        ),
        migrations.AlterField(
            model_name='text',
            name='edition_source',
            field=models.ManyToManyField(blank=True, to='corpus.Edition'),
        ),
    ]
