# Generated by Django 3.1.13 on 2022-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20220325_1143'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('number', 'text'), name='token_number_text'),
        ),
    ]
