# Generated by Django 3.1.13 on 2022-01-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_auto_20220118_0920'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='name_lastname',
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'last_name')},
        ),
    ]
