# Generated by Django 3.1.13 on 2022-03-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_auto_20220325_1147'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sentence',
            name='number_text',
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(fields=('number', 'text'), name='sentence_number_text'),
        ),
    ]
