# Generated by Django 3.1.13 on 2022-02-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_auto_20220201_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codex',
            name='title',
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
