# Generated by Django 4.1.2 on 2022-11-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_remove_historicalsection_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='translations',
            new_name='meanings',
        ),
    ]
