# Generated by Django 3.1.13 on 2021-09-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_historicalcodextext_historicaleditionsentence_historicaleditiontext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codextext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='codextext',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='editiontext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='editiontext',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcodextext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalcodextext',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicaleditiontext',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicaleditiontext',
            name='updated_at',
        ),
    ]
