# Generated by Django 3.1.13 on 2021-12-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_auto_20211213_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='author',
            new_name='authors',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='author',
        ),
        migrations.AddField(
            model_name='resource',
            name='authors',
            field=models.ManyToManyField(blank=True, to='corpus.Author'),
        ),
    ]
