# Generated by Django 3.1.13 on 2022-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_auto_20220608_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentcategory',
            name='category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcommentcategory',
            name='category',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
