# Generated by Django 3.1.13 on 2022-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_auto_20211222_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='features',
            new_name='morphological_annotation',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='syntax_annotations',
        ),
        migrations.RemoveField(
            model_name='historicaltoken',
            name='syntax_annotations',
        ),
        migrations.RemoveField(
            model_name='token',
            name='syntax_annotations',
        ),
        migrations.AddField(
            model_name='token',
            name='syntactic_annotation',
            field=models.ManyToManyField(blank=True, to='corpus.Dependency'),
        ),
        migrations.DeleteModel(
            name='SyntacticAnnotation',
        ),
    ]
