# Generated by Django 3.1.13 on 2022-05-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_auto_20220531_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='producer',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
