# Generated by Django 3.1.13 on 2022-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_auto_20220609_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codex',
            name='sigle',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcodex',
            name='sigle',
            field=models.CharField(db_index=True, max_length=5),
        ),
    ]
