# Generated by Django 3.1.13 on 2021-09-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_auto_20210917_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibentry',
            old_name='author',
            new_name='authors',
        ),
    ]
