# Generated by Django 3.1.13 on 2022-02-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_auto_20220202_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcodex',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicaledition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalsource',
            name='name',
        ),
        migrations.RemoveField(
            model_name='source',
            name='name',
        ),
    ]
