# Generated by Django 3.1.13 on 2022-01-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_auto_20220118_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='codex',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcodex',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
