# Generated by Django 3.1.13 on 2022-01-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0027_auto_20220103_1642'),
        ('corpus', '0006_auto_20220103_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lemma_token', to='dict.entry'),
        ),
    ]
