# Generated by Django 3.1.13 on 2022-06-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_auto_20220609_1021'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='textsigle',
            name='valid_sigle',
        ),
        migrations.RemoveConstraint(
            model_name='textsigle',
            name='valid_genre',
        ),
        migrations.AlterField(
            model_name='textsigle',
            name='genre',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='textsigle',
            name='sigle',
            field=models.CharField(max_length=10),
        ),
    ]
