# Generated by Django 3.1.13 on 2021-09-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_auto_20210920_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='side',
            name='folio',
        ),
        migrations.AlterField(
            model_name='historicalline',
            name='side',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.folio'),
        ),
        migrations.AlterField(
            model_name='line',
            name='side',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='corpus.folio'),
        ),
        migrations.DeleteModel(
            name='HistoricalSide',
        ),
        migrations.DeleteModel(
            name='Side',
        ),
    ]
