# Generated by Django 4.0.8 on 2022-12-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_alter_sentence_meanings'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltoken',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='word_token',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='token',
            name='root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='token',
            name='word_token',
            field=models.BooleanField(default=True),
        ),
    ]
