# Generated by Django 3.1.13 on 2022-01-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_auto_20220124_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codex',
            name='facsimile',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='scribe',
        ),
        migrations.AddField(
            model_name='codex',
            name='facsimiles',
            field=models.ManyToManyField(blank=True, related_name='codex_facsimiles', to='corpus.BibEntry'),
        ),
        migrations.AddField(
            model_name='codex',
            name='scribes',
            field=models.ManyToManyField(blank=True, related_name='codex_scribes', to='corpus.Author'),
        ),
    ]
