# Generated by Django 4.1.4 on 2022-12-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_historicaltoken_root_historicaltoken_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_line', to='corpus.line'),
        ),
    ]
