# Generated by Django 3.1.13 on 2022-06-01 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0007_historicaldependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBibEntry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical bib entry',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='bibentry',
            name='title_year_unique',
        ),
        migrations.RemoveField(
            model_name='bibentry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='bibentry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bibentry',
            name='year',
        ),
        migrations.RemoveField(
            model_name='codexpart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='codexpart',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='codexpart',
            name='part_type',
        ),
        migrations.RemoveField(
            model_name='historicalcodexpart',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalcodexpart',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='historicalcodexpart',
            name='part_type',
        ),
        migrations.AddField(
            model_name='codexpart',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalcodexpart',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='codexpart',
            name='codex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='codex_part_codex', to='corpus.codex'),
        ),
        migrations.AlterField(
            model_name='facsimile',
            name='bib_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facsimile_reference', to='corpus.bibentry'),
        ),
        migrations.AlterField(
            model_name='facsimile',
            name='codex_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facsimile_codex_part', to='corpus.codexpart'),
        ),
        migrations.AddField(
            model_name='historicalbibentry',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
