# Generated by Django 3.1.13 on 2022-02-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_auto_20220202_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcodextoken',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.text'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.text'),
        ),
        migrations.AddField(
            model_name='token',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_text', to='corpus.text'),
        ),
    ]
