# Generated by Django 3.1.13 on 2022-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_auto_20220328_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='slug',
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcorpus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='corpus',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='corpus_name_slug'),
        ),
    ]
