# Generated by Django 3.1.13 on 2022-06-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_auto_20220609_1059'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='text',
            name='valid_stage',
        ),
        migrations.AlterField(
            model_name='historicaltext',
            name='stage',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='text',
            name='stage',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
