# Generated by Django 3.1.13 on 2022-01-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_auto_20220124_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalline',
            old_name='side',
            new_name='folio',
        ),
        migrations.RenameField(
            model_name='line',
            old_name='side',
            new_name='folio',
        ),
    ]
