# Generated by Django 3.1.13 on 2022-06-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20220601_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codexpart',
            name='codex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_part_codex', to='corpus.codex'),
        ),
    ]
