# Generated by Django 3.1.13 on 2022-01-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20220124_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='name',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='featurevalue',
            old_name='name',
            new_name='identifier',
        ),
    ]
