# Generated by Django 3.1.13 on 2022-03-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_auto_20220328_1727'),
        ('corpus', '0008_auto_20220328_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoken',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='token',
            name='lemma',
        ),
        migrations.AddField(
            model_name='token',
            name='entries',
            field=models.ManyToManyField(blank=True, related_name='token_entries', to='dict.Entry'),
        ),
    ]
