# Generated by Django 3.1.13 on 2022-06-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20220609_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcodex',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicaledition',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicalsource',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='source',
            name='slug',
        ),
        migrations.AddField(
            model_name='historicalcodex',
            name='identifier',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='identifier',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='identifier',
            field=models.CharField(db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='identifier',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='bib_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_bib_entry', to='corpus.bibentry'),
        ),
    ]
