# Generated by Django 3.1.13 on 2022-02-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20220203_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='position_in_codex',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folio',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='position_in_codex',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.folio'),
        ),
        migrations.AddField(
            model_name='historicalline',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='line',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='corpus.line'),
        ),
        migrations.AlterField(
            model_name='section',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='corpus.section'),
        ),
        migrations.AlterField(
            model_name='token',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next', to='corpus.token'),
        ),
    ]
