# Generated by Django 3.1.13 on 2022-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_auto_20220613_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcodex',
            name='identifier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicaledition',
            name='identifier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsource',
            name='identifier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='identifier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
