# Generated by Django 3.1.13 on 2022-06-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_auto_20220601_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='text_sigle',
            new_name='text_sigles',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='copy_date',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='copy_place_latitude',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='copy_place_longitude',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='copy_place_name',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='library',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='scribes',
        ),
        migrations.RemoveField(
            model_name='codex',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='historicalcodex',
            name='copy_date',
        ),
        migrations.RemoveField(
            model_name='historicalcodex',
            name='copy_place_latitude',
        ),
        migrations.RemoveField(
            model_name='historicalcodex',
            name='copy_place_longitude',
        ),
        migrations.RemoveField(
            model_name='historicalcodex',
            name='copy_place_name',
        ),
        migrations.RemoveField(
            model_name='historicalcodex',
            name='library',
        ),
        migrations.RemoveField(
            model_name='historicalcodex',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='historicalcodex',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicaledition',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicalsource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='source',
            name='title',
        ),
        migrations.AddField(
            model_name='historicalcodex',
            name='bib_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='historicaledition',
            name='bib_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='historicalsource',
            name='bib_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry'),
        ),
        migrations.AddField(
            model_name='source',
            name='bib_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_bib_entry', to='corpus.bibentry'),
        ),
    ]
