# Generated by Django 3.1.13 on 2022-01-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_auto_20220125_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codextoken',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_token_line', to='corpus.line'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='codex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folio_codex', to='corpus.codex'),
        ),
        migrations.AlterField(
            model_name='line',
            name='folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_folio', to='corpus.folio'),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morphological_annotation_feature', to='corpus.feature'),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morphological_annotation_feature_value', to='corpus.featurevalue'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentence_text', to='corpus.text'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='tokens',
            field=models.ManyToManyField(related_name='sentence_tokens', to='corpus.Token'),
        ),
        migrations.AlterField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_corpus', to='corpus.corpus'),
        ),
        migrations.AlterField(
            model_name='text',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='text_resources', to='corpus.Resource'),
        ),
        migrations.AlterField(
            model_name='text',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='text_sources', to='corpus.Source'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_text_sigle', to='corpus.textsigle'),
        ),
    ]
