# Generated by Django 3.1.13 on 2022-02-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_auto_20220209_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codextoken',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codex_token_line', to='corpus.line'),
        ),
    ]
