# Generated by Django 3.1.13 on 2022-06-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_auto_20220601_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='text_resources', to='corpus.BibEntry'),
        ),
    ]
