# Generated by Django 3.1.13 on 2022-06-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_auto_20220613_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsection',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
