# Generated by Django 3.1.13 on 2022-06-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_auto_20220614_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['number']},
        ),
    ]
