# Generated by Django 3.1.13 on 2022-02-11 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_auto_20220211_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsection',
            name='container',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_container', to='corpus.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='corpus.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_source', to='corpus.source'),
        ),
    ]
