# Generated by Django 3.1.13 on 2022-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_auto_20220601_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibentry',
            name='url',
        ),
        migrations.RemoveField(
            model_name='historicalbibentry',
            name='url',
        ),
        migrations.AddField(
            model_name='bibentry',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbibentry',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
