# Generated by Django 3.1.13 on 2022-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0009_auto_20220503_1115'),
        ('corpus', '0011_auto_20220331_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='entries',
        ),
        migrations.AddField(
            model_name='token',
            name='meanings',
            field=models.ManyToManyField(blank=True, related_name='token_meanings', to='dict.Meaning'),
        ),
    ]
