# Generated by Django 3.1.13 on 2022-02-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_entry_related_entries'),
        ('corpus', '0012_auto_20220211_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_lemma', to='dict.entry'),
        ),
        migrations.AlterField(
            model_name='token',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='corpus.token'),
        ),
    ]
