# Generated by Django 3.1.13 on 2022-06-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_auto_20220614_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsection',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
