# Generated by Django 3.1.13 on 2022-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20220530_1338'),
        ('corpus', '0012_auto_20220601_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoken',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='token',
            name='lemma',
        ),
        migrations.AddField(
            model_name='token',
            name='lemmas',
            field=models.ManyToManyField(blank=True, related_name='token_lemma', to='dict.Lemma'),
        ),
    ]
