# Generated by Django 3.1.13 on 2022-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0010_auto_20220505_1217'),
        ('corpus', '0012_auto_20220505_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translations',
            field=models.ManyToManyField(related_name='sentence_translations', to='dict.Meaning'),
        ),
    ]
