# Generated by Django 3.1.13 on 2022-05-09 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0013_lemma_related_meanings'),
        ('corpus', '0013_auto_20220505_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='meanings',
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='lemma',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.lemma'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='meaning',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.meaning'),
        ),
        migrations.AddField(
            model_name='token',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_lemma', to='dict.lemma'),
        ),
        migrations.AddField(
            model_name='token',
            name='meaning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_meaning', to='dict.meaning'),
        ),
    ]
