# Generated by Django 3.1.13 on 2022-06-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20220530_1338'),
        ('corpus', '0013_auto_20220602_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='lemmas',
            field=models.ManyToManyField(blank=True, related_name='token_lemmas', to='dict.Lemma'),
        ),
    ]
