# Generated by Django 3.1.13 on 2022-02-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0013_auto_20220211_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codextoken',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codex_token_line', to='corpus.line'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='previous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='corpus.sentence'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_text_sigle', to='corpus.textsigle'),
        ),
    ]
