# Generated by Django 3.1.13 on 2022-06-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0013_auto_20220614_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsection',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
