# Generated by Django 3.1.13 on 2022-02-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_entry_related_entries'),
        ('corpus', '0014_auto_20220211_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcodextoken',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.language'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.language'),
        ),
        migrations.AddField(
            model_name='token',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_language', to='dict.language'),
        ),
    ]
