# Generated by Django 3.1.13 on 2022-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0013_lemma_related_meanings'),
        ('corpus', '0014_auto_20220509_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoken',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='token',
            name='meaning',
        ),
        migrations.AddField(
            model_name='token',
            name='meanings',
            field=models.ManyToManyField(blank=True, related_name='token_meanings', to='dict.Meaning'),
        ),
    ]
