# Generated by Django 3.1.13 on 2022-06-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0014_auto_20220614_1038'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folio',
            name='identifier_facsimile',
        ),
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(fields=('identifier', 'facsimile', 'number'), name='identifier_facsimile_number'),
        ),
    ]
