# Generated by Django 3.1.13 on 2022-06-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0015_auto_20220620_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsection',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.AlterField(
            model_name='historicalsection',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
