# Generated by Django 3.1.13 on 2022-02-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0003_auto_20220214_1518'),
        ('corpus', '0016_auto_20220214_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsentence',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='translation',
        ),
        migrations.AddField(
            model_name='sentence',
            name='translations',
            field=models.ManyToManyField(related_name='sentence_translations', to='dict.Translation'),
        ),
    ]
