# Generated by Django 3.1.13 on 2022-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0017_auto_20220214_1518'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='codextoken',
            constraint=models.UniqueConstraint(fields=('line', 'position'), name='line_position'),
        ),
    ]
