# Generated by Django 3.1.13 on 2022-02-16 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0018_auto_20220215_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codex',
            name='facsimiles',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='codex',
        ),
        migrations.RemoveField(
            model_name='folio',
            name='position_in_codex',
        ),
        migrations.RemoveField(
            model_name='historicalfolio',
            name='codex',
        ),
        migrations.RemoveField(
            model_name='historicalfolio',
            name='position_in_codex',
        ),
        migrations.CreateModel(
            name='HistoricalFacsimile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.bibentry')),
            ],
            options={
                'verbose_name': 'historical facsimile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCodexPart',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('numeration', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('codex', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codex')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical codex part',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Facsimile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facsimile_references', to='corpus.bibentry')),
            ],
        ),
        migrations.CreateModel(
            name='CodexPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('numeration', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('codex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codex_part_codex', to='corpus.codex')),
            ],
        ),
        migrations.AddField(
            model_name='folio',
            name='facsimile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folio_facsimile', to='corpus.facsimile'),
        ),
        migrations.AddField(
            model_name='historicalfolio',
            name='facsimile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.facsimile'),
        ),
    ]
