# Generated by Django 3.1.13 on 2022-02-16 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0019_auto_20220216_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codexpart',
            old_name='numeration',
            new_name='part_number',
        ),
        migrations.RenameField(
            model_name='historicalcodexpart',
            old_name='numeration',
            new_name='part_number',
        ),
        migrations.RemoveField(
            model_name='codexpart',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='codexpart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicalcodexpart',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicalcodexpart',
            name='title',
        ),
        migrations.AddField(
            model_name='codexpart',
            name='part_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facsimile',
            name='codex_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facsimiles', to='corpus.codexpart'),
        ),
        migrations.AddField(
            model_name='historicalcodexpart',
            name='part_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalfacsimile',
            name='codex_part',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codexpart'),
        ),
    ]
