# Generated by Django 3.1.13 on 2022-02-16 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0021_auto_20220216_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facsimile',
            name='codex_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facsimile_codex_part', to='corpus.codexpart'),
        ),
        migrations.AlterField(
            model_name='facsimile',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facsimile_reference', to='corpus.bibentry'),
        ),
    ]
