# Generated by Django 3.1.13 on 2022-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0022_auto_20220216_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibentry',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='bib_entry_authors', to='corpus.Author'),
        ),
        migrations.AddConstraint(
            model_name='bibentry',
            constraint=models.UniqueConstraint(fields=('title', 'year'), name='title_year_unique'),
        ),
    ]
