# Generated by Django 3.1.13 on 2022-02-16 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0023_auto_20220216_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facsimile',
            old_name='reference',
            new_name='bib_entry',
        ),
        migrations.RenameField(
            model_name='historicalfacsimile',
            old_name='reference',
            new_name='bib_entry',
        ),
    ]
