# Generated by Django 3.1.13 on 2022-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0024_auto_20220216_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibentry',
            name='year',
            field=models.IntegerField(),
        ),
    ]
