# Generated by Django 3.1.13 on 2022-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0025_auto_20220216_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibentry',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalline',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='line',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
