# Generated by Django 3.1.13 on 2022-02-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0027_auto_20220216_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facsimile',
            name='bib_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facsimile_reference', to='corpus.bibentry'),
        ),
    ]
