# Generated by Django 3.1.13 on 2022-02-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0028_auto_20220216_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcodextoken',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='language',
            field=models.CharField(blank=True, choices=[('akk', 'Akkadian'), ('arc', 'Imperial Aramaic (700-300 BCE), Official Aramaic (700-300 BCE)'), ('ave', 'Avestan'), ('eng', 'English'), ('deu', 'German'), ('fra', 'French'), ('grc', 'Ancient Greek (to 1453)'), ('ita', 'Italian'), ('pal', 'Pahlavi'), ('spa', 'Spanish'), ('xpr', 'Parthian')], max_length=3, null=True),
        ),
    ]
