# Generated by Django 3.1.13 on 2022-02-19 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0029_auto_20220217_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codextoken',
            name='line',
        ),
        migrations.RemoveField(
            model_name='codextoken',
            name='token_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='line',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='text',
        ),
        migrations.RemoveField(
            model_name='historicalcodextoken',
            name='token_ptr',
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='line',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='position_in_line',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_line', to='corpus.line'),
        ),
        migrations.AddField(
            model_name='token',
            name='position_in_line',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('line', 'position_in_line'), name='line_position'),
        ),
        migrations.DeleteModel(
            name='CodexToken',
        ),
        migrations.DeleteModel(
            name='HistoricalCodexToken',
        ),
    ]
