# Generated by Django 3.1.13 on 2022-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0030_auto_20220219_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
