# Generated by Django 3.1.13 on 2022-02-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0032_auto_20220221_1202'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folio',
            constraint=models.UniqueConstraint(fields=('identifier', 'facsimile'), name='identifier_facsimile'),
        ),
        migrations.AddConstraint(
            model_name='line',
            constraint=models.UniqueConstraint(fields=('number', 'folio'), name='number_folio'),
        ),
    ]
