# Generated by Django 4.1.4 on 2023-02-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='rel',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldependency',
            name='rel',
            field=models.CharField(max_length=25),
        ),
    ]
