# Generated by Django 4.1.4 on 2023-02-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='morphological_annotation',
            new_name='morphological_annotations',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='syntactic_annotation',
            new_name='syntactic_annotations',
        ),
    ]
