# Generated by Django 4.1.4 on 2023-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_alter_bibentry_key_alter_historicalbibentry_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsigle',
            name='genre',
            field=models.CharField(max_length=10),
        ),
    ]
