# Generated by Django 4.1.4 on 2023-02-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('text', 'identifier'), name='section_text_identifier'),
        ),
    ]
