# Generated by Django 4.1.4 on 2023-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_section_section_text_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['identifier']},
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('type', 'identifier'), name='source_type_identifier'),
        ),
    ]
