# Generated by Django 4.1.4 on 2023-02-21 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_rename_corpus_sect_section_aa3b63_idx_corpus_sect_section_d08af5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sectiontoken',
            new_name='corpus_sect_section_aa3b63_idx',
            old_name='corpus_sect_section_d08af5_idx',
        ),
        migrations.RenameIndex(
            model_name='sectiontoken',
            new_name='corpus_sect_token_i_b1fd0a_idx',
            old_name='corpus_sect_token_i_1696d1_idx',
        ),
        migrations.RenameIndex(
            model_name='sectiontoken',
            new_name='corpus_sect_section_782af8_idx',
            old_name='corpus_sect_section_26f719_idx',
        ),
        migrations.AlterModelTable(
            name='section',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sectiontoken',
            table=None,
        ),
    ]
