# Generated by Django 4.1.4 on 2023-01-20 06:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_alter_textsigle_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltext',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='text',
            name='language',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None),
        ),
    ]
