# Generated by Django 4.1.4 on 2023-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_rename_morphological_annotation_token_morphological_annotations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltext',
            name='text_sigle',
        ),
        migrations.RemoveField(
            model_name='text',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='text',
            name='text_sigle',
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltext',
            name='stage',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='text',
            name='stage',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
