# Generated by Django 4.1.4 on 2023-02-09 08:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0003_dependency_head_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalMorphologicalAnnotation',
            new_name='HistoricalPostFeature',
        ),
        migrations.RenameModel(
            old_name='MorphologicalAnnotation',
            new_name='PostFeature',
        ),
        migrations.AlterModelOptions(
            name='historicalpostfeature',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical post feature', 'verbose_name_plural': 'historical post features'},
        ),
    ]
