# Generated by Django 4.1.4 on 2023-02-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_remove_historicaltext_text_sigle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text_sigle',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='text_sigle',
        ),
        migrations.DeleteModel(
            name='TextSigle',
        ),
    ]
