# Generated by Django 4.1.4 on 2023-02-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_alter_source_options_source_source_type_identifier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='text',
            name='corpus_title',
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
