# Generated by Django 4.1.4 on 2023-02-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_remove_bibentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.pos'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.token'),
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together={('feature', 'pos')},
        ),
    ]
