# Generated by Django 4.1.4 on 2023-01-28 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_alter_historicaltext_language_alter_text_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facsimile',
            name='codex_part',
        ),
        migrations.RemoveField(
            model_name='historicalfacsimile',
            name='codex_part',
        ),
        migrations.AddField(
            model_name='facsimile',
            name='codex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facsimile_codex_part', to='corpus.codex'),
        ),
        migrations.AddField(
            model_name='historicalfacsimile',
            name='codex',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='corpus.codex'),
        ),
    ]
