# Generated by Django 4.1.4 on 2023-03-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
        ('corpus', '0005_comment_user_historicalcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlemma',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_lemma_lemma', to='dict.lemma'),
        ),
        migrations.AlterField(
            model_name='tokenlemma',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_lemma_token', to='corpus.token'),
        ),
        migrations.AlterField(
            model_name='tokenmeaning',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_meaning_meaning', to='dict.meaning'),
        ),
        migrations.AlterField(
            model_name='tokenmeaning',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_meaning_token', to='corpus.token'),
        ),
    ]
