# Generated by Django 4.1.4 on 2023-02-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_alter_feature_pos_alter_feature_token_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set(),
        ),
    ]
