# Generated by Django 4.1.4 on 2023-02-13 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0005_remove_text_corpus_title_historicaltext_identifier_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostFeature',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='HistoricalPostFeature',
            new_name='HistoricalFeature',
        ),
        migrations.AlterModelOptions(
            name='historicalfeature',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical feature', 'verbose_name_plural': 'historical features'},
        ),
        migrations.RemoveField(
            model_name='token',
            name='postfeatures',
        ),
        migrations.AddField(
            model_name='token',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='token_features', to='corpus.feature'),
        ),
    ]
