# Generated by Django 4.1.4 on 2023-03-01 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
        ('corpus', '0006_alter_tokenlemma_lemma_alter_tokenlemma_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlemma',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.lemma'),
        ),
        migrations.AlterField(
            model_name='tokenlemma',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.token'),
        ),
        migrations.AlterField(
            model_name='tokenmeaning',
            name='meaning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dict.meaning'),
        ),
        migrations.AlterField(
            model_name='tokenmeaning',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.token'),
        ),
    ]
