# Generated by Django 4.1.4 on 2023-02-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_alter_feature_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_pos', to='corpus.pos'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_token', to='corpus.token'),
        ),
    ]
