# Generated by Django 4.1.4 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_rename_postfeature_feature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='historicalsection',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltext',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltext',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('corpus', 'identifier'), name='text_corpus_identifier'),
        ),
    ]
