# Generated by Django 4.1.4 on 2023-02-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_alter_text_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependency_head', to='corpus.token'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='rel',
            field=models.CharField(blank=True, choices=[('acl', 'ACL'), ('acl:cleft', 'ACL_CLEFT'), ('acl:relcl', 'ACL_RELCL'), ('advcl', 'ADVCL'), ('advcl:cleft', 'ADVCL_CLEFT'), ('advmod', 'ADVMOD'), ('advmod:emph', 'ADVMOD_EMPH'), ('advmod:lmod', 'ADVMOD_LMOD'), ('advmod:tmod', 'ADVMOD_TMOD'), ('amod', 'AMOD'), ('appos', 'APPOS'), ('aux', 'AUX'), ('aux:pass', 'AUX_PASS'), ('case', 'CASE'), ('cc', 'CC'), ('cc:nc', 'CC_NC'), ('cc:preconj', 'CC_PRECONJ'), ('ccomp', 'CCOMP'), ('compound:lvc', 'COMPOUND_LVC'), ('compound:redup', 'COMPOUND_REDUP'), ('compound:svc', 'COMPOUND_SVC'), ('conj', 'CONJ'), ('cop', 'COP'), ('csubj', 'CSUBJ'), ('csubj:pass', 'CSUBJ_PASS'), ('dep', 'DEP'), ('det', 'DET'), ('det:poss', 'DET_POSS'), ('discourse', 'DISCOURSE'), ('dislocated', 'DISLOCATED'), ('dislocated:res', 'DISLOCATED_RES'), ('dislocated:topic', 'DISLOCATED_TOPIC'), ('expl', 'EXPL'), ('fixed', 'FIXED'), ('flat', 'FLAT'), ('goeswith', 'GOESWITH'), ('iobj', 'IOBJ'), ('mark', 'MARK'), ('nmod', 'NMOD'), ('nsubj', 'NSUBJ'), ('nsubj:emph', 'NSUBJ_EMPH'), ('nsubj:outer', 'NSUBJ_OUTER'), ('nsubj:pass', 'NSUBJ_PASS'), ('nsubj:xsubj', 'NSUBJ_XSUBJ'), ('nummod', 'NUMMOD'), ('obj', 'OBJ'), ('obj:emph', 'OBJ_EMPH'), ('obl', 'OBL'), ('obl:agent', 'OBL_AGENT'), ('obl:emph', 'OBL_EMPH'), ('obl:lmod', 'OBL_LMOD'), ('obl:tmod', 'OBL_TMOD'), ('orphan', 'ORPHAN'), ('parataxis', 'PARATAXIS'), ('punct', 'PUNCT'), ('reparandum', 'REPARANDUM'), ('reparandum:res', 'REPARANDUM_RES'), ('root', 'ROOT'), ('vocative', 'VOCATIVE'), ('xcomp', 'XCOMP')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldependency',
            name='rel',
            field=models.CharField(blank=True, choices=[('acl', 'ACL'), ('acl:cleft', 'ACL_CLEFT'), ('acl:relcl', 'ACL_RELCL'), ('advcl', 'ADVCL'), ('advcl:cleft', 'ADVCL_CLEFT'), ('advmod', 'ADVMOD'), ('advmod:emph', 'ADVMOD_EMPH'), ('advmod:lmod', 'ADVMOD_LMOD'), ('advmod:tmod', 'ADVMOD_TMOD'), ('amod', 'AMOD'), ('appos', 'APPOS'), ('aux', 'AUX'), ('aux:pass', 'AUX_PASS'), ('case', 'CASE'), ('cc', 'CC'), ('cc:nc', 'CC_NC'), ('cc:preconj', 'CC_PRECONJ'), ('ccomp', 'CCOMP'), ('compound:lvc', 'COMPOUND_LVC'), ('compound:redup', 'COMPOUND_REDUP'), ('compound:svc', 'COMPOUND_SVC'), ('conj', 'CONJ'), ('cop', 'COP'), ('csubj', 'CSUBJ'), ('csubj:pass', 'CSUBJ_PASS'), ('dep', 'DEP'), ('det', 'DET'), ('det:poss', 'DET_POSS'), ('discourse', 'DISCOURSE'), ('dislocated', 'DISLOCATED'), ('dislocated:res', 'DISLOCATED_RES'), ('dislocated:topic', 'DISLOCATED_TOPIC'), ('expl', 'EXPL'), ('fixed', 'FIXED'), ('flat', 'FLAT'), ('goeswith', 'GOESWITH'), ('iobj', 'IOBJ'), ('mark', 'MARK'), ('nmod', 'NMOD'), ('nsubj', 'NSUBJ'), ('nsubj:emph', 'NSUBJ_EMPH'), ('nsubj:outer', 'NSUBJ_OUTER'), ('nsubj:pass', 'NSUBJ_PASS'), ('nsubj:xsubj', 'NSUBJ_XSUBJ'), ('nummod', 'NUMMOD'), ('obj', 'OBJ'), ('obj:emph', 'OBJ_EMPH'), ('obl', 'OBL'), ('obl:agent', 'OBL_AGENT'), ('obl:emph', 'OBL_EMPH'), ('obl:lmod', 'OBL_LMOD'), ('obl:tmod', 'OBL_TMOD'), ('orphan', 'ORPHAN'), ('parataxis', 'PARATAXIS'), ('punct', 'PUNCT'), ('reparandum', 'REPARANDUM'), ('reparandum:res', 'REPARANDUM_RES'), ('root', 'ROOT'), ('vocative', 'VOCATIVE'), ('xcomp', 'XCOMP')], max_length=25, null=True),
        ),
    ]
