# Generated by Django 4.1.4 on 2023-02-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_alter_feature_pos_alter_feature_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.section')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.token')),
            ],
        ),
        migrations.AddIndex(
            model_name='sectiontoken',
            index=models.Index(fields=['section', 'token'], name='corpus_sect_section_782af8_idx'),
        ),
    ]
