# Generated by Django 4.1.4 on 2023-02-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_alter_dependency_head_alter_dependency_rel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='rel',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldependency',
            name='rel',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
