# Generated by Django 4.1.4 on 2023-03-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_historicalimage_page_image_page'),
        ('corpus', '0008_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltoken',
            name='image',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='images.image'),
        ),
        migrations.AddField(
            model_name='token',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_image', to='images.image'),
        ),
    ]
