# Generated by Django 4.1.4 on 2023-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_historicaltoken_image_token_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltext',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
