# Generated by Django 4.1.4 on 2023-07-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_historicaltext_version_text_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltoken',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='transliteration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='transliteration',
            field=models.TextField(blank=True),
        ),
    ]
