# Generated by Django 4.1.4 on 2023-07-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_alter_historicaltoken_transcription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltoken',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='transliteration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='transliteration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
