# Generated by Django 4.2.2 on 2023-08-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_alter_historicaltoken_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='enhanced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldependency',
            name='enhanced',
            field=models.BooleanField(default=False),
        ),
    ]
