# Generated by Django 4.2.2 on 2023-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0014_remove_token_token_number_text_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['type'], name='corpus_sect_type_49ae9a_idx'),
        ),
    ]
