# Generated by Django 4.2.7 on 2023-11-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0016_feature_corpus_feat_feature_c0e53a_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='sectiontoken',
            options={'ordering': ['section', 'token']},
        ),
    ]
