# Generated by Django 4.2.7 on 2023-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0011_lemmasense_historicallemmasense_and_more'),
        ('corpus', '0018_tokensense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='meanings',
        ),
        migrations.AddField(
            model_name='token',
            name='senses',
            field=models.ManyToManyField(blank=True, related_name='token_senses', through='corpus.TokenSense', to='dict.sense'),
        ),
    ]
