# Generated by Django 4.2.7 on 2023-11-06 13:12

from django.db import migrations, models
import django.db.models.deletion


def migrate_section_meanings_to_senses(apps, schema_editor):
    Section = apps.get_model('corpus', 'Section')
    Meaning = apps.get_model('dict', 'Meaning')
    Sense = apps.get_model('dict', 'Sense')

    for section in Section.objects.all():
        for meaning in section.meanings.all():
            # Make sure the corresponding Sense exists for each Meaning
            sense = Sense.objects.get(id=meaning.id)
            section.senses.add(sense)
            section.save()  # Save the section with the new Sense relation

def migrate_comment_meanings_to_senses(apps, schema_editor):
    Comment = apps.get_model('corpus', 'Comment')
    Meaning = apps.get_model('dict', 'Meaning')
    Sense = apps.get_model('dict', 'Sense')

    for comment in Comment.objects.filter(meaning__isnull=False):
        meaning_id = comment.meaning_id  # Presuming 'meaning_id' is the FK field
        # Get the corresponding Sense object for the Meaning
        sense = Sense.objects.get(id=meaning_id)
        comment.sense = sense
        comment.save()  # Save the comment with the new Sense relation


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0011_lemmasense_historicallemmasense_and_more'),
        ('corpus', '0019_remove_token_meanings_token_senses'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_sense', to='dict.sense'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='sense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.sense'),
        ),
        migrations.AddField(
            model_name='section',
            name='senses',
            field=models.ManyToManyField(related_name='section_senses', to='dict.sense'),
        ),
        migrations.RunPython(migrate_section_meanings_to_senses),
        migrations.RunPython(migrate_comment_meanings_to_senses),
    ]
