# Generated by Django 4.2.7 on 2023-12-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0023_remove_section_corpus_sect_type_6c30d1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['series']},
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='corpus_sect_type_775d9b_idx',
        ),
        migrations.AlterField(
            model_name='source',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='source_references', to='corpus.bibentry'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['type', 'text'], name='corpus_sect_type_6c30d1_idx'),
        ),
    ]
