# Generated by Django 4.2.7 on 2024-02-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0025_alter_historicalsection_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={},
        ),
        migrations.AddField(
            model_name='section',
            name='related_to',
            field=models.ManyToManyField(related_name='section_related_to', to='corpus.section'),
        ),
    ]
