# Generated by Django 4.2.7 on 2024-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0026_alter_text_options_section_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltoken',
            name='avestan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='transcription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='transliteration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='avestan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='transcription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='transliteration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
