# Generated by Django 4.2.7 on 2024-02-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0027_alter_historicaltoken_avestan_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['number'], name='corpus_sect_number_4da742_idx'),
        ),
    ]
