# Generated by Django 4.2.7 on 2024-02-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0028_section_corpus_sect_number_4da742_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='section',
            name='corpus_sect_type_6c30d1_idx',
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['id', 'number', 'type'], name='corpus_sect_id_9c52ad_idx'),
        ),
    ]
