# Generated by Django 4.2.7 on 2024-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0029_remove_section_corpus_sect_type_6c30d1_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['id', 'number', 'text', 'language', 'transcription'], name='corpus_toke_id_f4fc96_idx'),
        ),
    ]
