# Generated by Django 4.2.7 on 2024-02-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0031_section_corpus_sect_type_6c30d1_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['identifier'], name='corpus_sect_identif_d7915e_idx'),
        ),
    ]
