# Generated by Django 4.2.7 on 2024-02-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0032_section_corpus_sect_identif_d7915e_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='section',
            name='corpus_sect_id_9c52ad_idx',
        ),
    ]
