# Generated by Django 4.2.7 on 2024-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0033_remove_section_corpus_sect_id_9c52ad_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='token',
            name='corpus_toke_id_f4fc96_idx',
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['number', 'text', 'language', 'transcription'], name='corpus_toke_number_1288fd_idx'),
        ),
    ]
