# Generated by Django 4.2.7 on 2024-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0042_remove_text_text_corpus_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='section',
            name='corpus_sect_type_6c30d1_idx',
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['text', 'type'], name='corpus_sect_text_id_567c68_idx'),
        ),
    ]
