# Generated by Django 4.2.7 on 2024-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0043_remove_section_corpus_sect_type_6c30d1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='stage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
