# Generated by Django 4.2.7 on 2024-07-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_modified_by'),
        ('dict', '0017_lemma_modified_by_sense_modified_by'),
        ('corpus', '0044_alter_text_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_tokens', to='images.image'),
        ),
        migrations.AlterField(
            model_name='token',
            name='lemmas',
            field=models.ManyToManyField(blank=True, related_name='lemma_tokens', through='corpus.TokenLemma', to='dict.lemma'),
        ),
        migrations.AlterField(
            model_name='token',
            name='senses',
            field=models.ManyToManyField(blank=True, related_name='sense_tokens', through='corpus.TokenSense', to='dict.sense'),
        ),
        migrations.AlterField(
            model_name='token',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_tokens', to='corpus.text'),
        ),
    ]
