# Generated by Django 3.1.13 on 2021-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0017_delete_tokensemantics'),
        ('edition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsentence',
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='tokens',
        ),
        migrations.AddField(
            model_name='sentence',
            name='tokens',
            field=models.ManyToManyField(related_name='edition_tokens', to='codex.Token'),
        ),
    ]
