# Generated by Django 4.2.7 on 2023-11-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_input', models.CharField(max_length=255)),
                ('criteria_value', models.IntegerField(default=0)),
                ('criteria_scope', models.CharField(max_length=255)),
                ('lemmas_word', models.CharField(max_length=255)),
                ('toggle_field', models.BooleanField(default=False)),
            ],
        ),
    ]
