# Generated by Django 4.2.7 on 2023-11-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_toggle_field_searchcriteria_remove_stopwords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchcriteria',
            old_name='field',
            new_name='query_field',
        ),
        migrations.RenameField(
            model_name='searchcriteria',
            old_name='value',
            new_name='query_value',
        ),
        migrations.RemoveField(
            model_name='searchcriteria',
            name='lemma_word',
        ),
        migrations.RemoveField(
            model_name='searchcriteria',
            name='meaning_word',
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='lemma_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='meaning_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='feature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='feature_value',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='pos_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
