# Generated by Django 4.2.7 on 2023-12-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_searchcriteria_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance_type',
            field=models.CharField(blank=True, choices=[('both', 'Search on both sides'), ('left', 'Before anchor'), ('right', 'After anchor')], default='both'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='logical_operator',
            field=models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], default='AND'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='query_field',
            field=models.CharField(choices=[('id', 'ID'), ('number', 'Number'), ('numberInSentence', 'Number in sentence'), ('root', 'Root'), ('language', 'Language'), ('transcription', 'Transcription'), ('transliteration', 'Transliteration'), ('avestan', 'Avestan'), ('gloss', 'Gloss'), ('created_at', 'Created')], default='transcription'),
        ),
    ]
