# Generated by Django 4.2.7 on 2023-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_searchcriteria_distance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance_type',
            field=models.CharField(blank=True, choices=[('both', 'Search on both sides'), ('before', 'Before anchor'), ('after', 'After anchor')], default='both'),
        ),
    ]
