# Generated by Django 4.2.7 on 2023-12-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_searchcriteria_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance_type',
            field=models.CharField(blank=True, choices=[(0, None), ('both', 'Search on both sides'), ('before', 'Before anchor'), ('after', 'After anchor')], default='both'),
        ),
    ]
