# Generated by Django 4.2.7 on 2023-12-18 08:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0011_searchsession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='queries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together={('user', 'session_id', 'queries')},
        ),
    ]
