# Generated by Django 4.2.7 on 2024-01-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_alter_searchsession_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcriteria',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance_type',
            field=models.CharField(choices=[('both', 'On either side of anchor'), ('before', 'Preceding anchor'), ('after', 'Following anchor')], default='both'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='query_field',
            field=models.CharField(choices=[('avestan', 'Avestan'), ('gloss', 'Gloss'), ('id', 'ID'), ('language', 'Language'), ('number', 'Number'), ('numberInSentence', 'Number in sentence'), ('root', 'Root'), ('transcription', 'Transcription'), ('transliteration', 'Transliteration')], default='transcription'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='query_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('prefix', 'Prefix'), ('suffix', 'Suffix'), ('regex', 'Regex')], default='exact'),
        ),
    ]
