# Generated by Django 4.2.7 on 2024-01-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_searchcriteria_case_sensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance_type',
            field=models.CharField(blank=True, choices=[('both', 'On either side of anchor'), ('before', 'Preceding anchor'), ('after', 'Following anchor')], default='both'),
        ),
    ]
