# Generated by Django 4.2.7 on 2024-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alter_searchcriteria_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='distance',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
