# Generated by Django 4.2.7 on 2024-01-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_alter_searchcriteria_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcriteria',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='language',
            field=models.CharField(blank=True, choices=[('', 'All'), ('pal', 'Middle Persian'), ('arc', 'Imperial Aramaic'), ('ave', 'Avestan'), ('grc', 'Ancient Greek'), ('xpr', 'Parthian'), ('prp', 'Parsi'), ('ara', 'Arabic'), ('guj', 'Gujarati'), ('san', 'Sanskrit'), ('eng', 'English'), ('fra', 'French'), ('deu', 'German'), ('ita', 'Italian'), ('spa', 'Spanish')], default=''),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='query_field',
            field=models.CharField(choices=[('id', 'ID'), ('transcription', 'Transcription'), ('transliteration', 'Transliteration'), ('avestan', 'Avestan'), ('gloss', 'Gloss')], default='transcription'),
        ),
    ]
