# Generated by Django 4.2.7 on 2024-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_searchcriteria_is_root_searchcriteria_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='logical_operator',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND'),
        ),
    ]
