# Generated by Django 4.2.7 on 2024-01-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_alter_searchcriteria_logical_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='logical_operator',
            field=models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR')], default='AND'),
        ),
    ]
