# Generated by Django 4.2.7 on 2024-01-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_alter_searchcriteria_logical_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchcriteria',
            old_name='is_root',
            new_name='root',
        ),
    ]
