# Generated by Django 4.2.7 on 2024-02-04 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0020_rename_is_root_searchcriteria_root'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together={('user', 'session_id', 'queries')},
        ),
    ]
