# Generated by Django 4.2.7 on 2024-02-04 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0021_alter_searchsession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='searchsession',
            name='filters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together={('user', 'session_id', 'queries', 'filters')},
        ),
    ]
