# Generated by Django 4.2.7 on 2024-02-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_remove_searchsession_formset_searchsession_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchsession',
            name='filters',
        ),
    ]
