# Generated by Django 4.2.7 on 2024-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_remove_searchsession_filters'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='searchsession',
            name='user',
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='logical_operator',
            field=models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR'), ('NOT', 'NOT')], default='AND'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='query_field',
            field=models.CharField(choices=[('id', 'ID'), ('transcription', 'Transcription'), ('transliteration', 'Transliteration'), ('avestan', 'Avestan'), ('gloss', 'Gloss'), ('lemmas__word', 'Lemma'), ('senses__sense', 'Sense'), ('token_pos__pos', 'POS')], default='transcription'),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='query_type',
            field=models.CharField(choices=[('exact', 'Exact'), ('contains', 'Contains'), ('startswith', 'Prefix'), ('endswith', 'Suffix'), ('regex', 'Regex')], default='exact'),
        ),
        migrations.DeleteModel(
            name='ResultFilter',
        ),
        migrations.DeleteModel(
            name='SearchSession',
        ),
    ]
