# Generated by Django 4.2.7 on 2024-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0022_alter_searchsession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchsession',
            name='formset',
            field=models.ManyToManyField(blank=True, to='search.searchcriteria'),
        ),
    ]
