# Generated by Django 4.2.7 on 2024-02-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_searchsession_formset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchsession',
            name='formset',
        ),
    ]
