# Generated by Django 3.1.13 on 2021-08-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='morphologicalannotation',
            constraint=models.UniqueConstraint(fields=('pos', 'feature', 'feature_value'), name='pos_feature_feature_value'),
        ),
    ]
