# Generated by Django 3.1.13 on 2021-08-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='tkn',
            new_name='token',
        ),
    ]
