# Generated by Django 3.1.13 on 2021-09-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTokenContainer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('container_type', models.CharField(choices=[('SEN', 'Sentence'), ('PAR', 'Paragraph'), ('CLA', 'Clause'), ('PHR', 'Phrase')], max_length=3)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical token container',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TokenContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_type', models.CharField(choices=[('SEN', 'Sentence'), ('PAR', 'Paragraph'), ('CLA', 'Clause'), ('PHR', 'Phrase')], max_length=3)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('tokens', models.ManyToManyField(to='codex.CodexToken')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalchapter',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchapter',
            name='text',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsentence',
            name='section',
        ),
        migrations.RemoveField(
            model_name='historicalstrophe',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalstrophe',
            name='text',
        ),
        migrations.RemoveField(
            model_name='historicalverse',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalverse',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='strophe',
            name='text',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='verse',
        ),
        migrations.RemoveField(
            model_name='historicalsection',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='historicalsection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='section_container',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='codex.section'),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='section_type',
            field=models.CharField(choices=[('SEN', 'Sentence'), ('CHA', 'Chapter'), ('VER', 'Verse'), ('STR', 'Strophe')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='text',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='codex.text'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='codex.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('SEN', 'Sentence'), ('CHA', 'Chapter'), ('VER', 'Verse'), ('STR', 'Strophe')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.text'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='HistoricalChapter',
        ),
        migrations.DeleteModel(
            name='HistoricalSentence',
        ),
        migrations.DeleteModel(
            name='HistoricalStrophe',
        ),
        migrations.DeleteModel(
            name='HistoricalVerse',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='Strophe',
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
    ]
