# Generated by Django 3.1.13 on 2021-09-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='token',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='token',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='HistoricalToken',
        ),
        migrations.DeleteModel(
            name='TokenUser',
        ),
    ]
