# Generated by Django 3.1.13 on 2021-09-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='feature_name_value',
        ),
        migrations.RemoveConstraint(
            model_name='featurevalue',
            name='featurevalue_name_value',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='value',
        ),
        migrations.RemoveField(
            model_name='featurevalue',
            name='value',
        ),
        migrations.AlterField(
            model_name='featurevalue',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='avestan',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='pos',
            field=models.CharField(choices=[('ADJ', 'ADJ'), ('ADP', 'ADP'), ('ADV', 'ADV'), ('AUX', 'AUX'), ('CCONJ', 'CCONJ'), ('DET', 'DET'), ('INTJ', 'INTJ'), ('NOUN', 'NOUN'), ('NUM', 'NUM'), ('PART', 'PART'), ('PRON', 'PRON'), ('PROPN', 'PROPN'), ('PUNCT', 'PUNCT'), ('SCONJO', 'SCONJO'), ('SYM', 'SYM'), ('VERB', 'VERB'), ('X', 'X')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='avestan',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('name',), name='feature_name'),
        ),
        migrations.AddConstraint(
            model_name='featurevalue',
            constraint=models.UniqueConstraint(fields=('name',), name='featurevalue_name'),
        ),
    ]
