# Generated by Django 3.1.13 on 2021-08-23 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codex.section'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='tokens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prose_tokens', to='codex.token'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='tokens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_tokens', to='codex.token'),
        ),
    ]
