# Generated by Django 3.1.13 on 2021-09-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20210907_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folio',
            old_name='codex_id',
            new_name='codex',
        ),
        migrations.RenameField(
            model_name='historicalfolio',
            old_name='codex_id',
            new_name='codex',
        ),
        migrations.RenameField(
            model_name='historicalside',
            old_name='folio_id',
            new_name='folio',
        ),
        migrations.RenameField(
            model_name='side',
            old_name='folio_id',
            new_name='folio',
        ),
    ]
