# Generated by Django 3.1.13 on 2021-08-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_auto_20210827_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='morph_annotations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.morphologicalannotation'),
        ),
        migrations.AlterField(
            model_name='token',
            name='syntax_annotations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.syntacticannotation'),
        ),
    ]
