# Generated by Django 3.1.13 on 2021-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_auto_20210827_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='head',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
