# Generated by Django 3.1.13 on 2021-09-15 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_auto_20210914_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSigle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigle', models.CharField(choices=[('AM', 'AM'), ('AOD', 'AŌD'), ('Aog', 'Aog'), ('ASS', 'ASS'), ('AWM', 'AWM'), ('AWN', 'AWN'), ('AZ', 'AZ'), ('CHP', 'CHP'), ('DA', 'DA'), ('Dd', 'Dd'), ('Dk3', 'Dk3'), ('Dk4', 'Dk4'), ('Dk5', 'Dk5'), ('Dk6', 'Dk6'), ('Dk7', 'Dk7'), ('Dk8', 'Dk8'), ('Dk9', 'Dk9'), ('DkC', 'DkC'), ('DMX', 'DMX'), ('ENN', 'ENN'), ('GA', 'GA'), ('GBd', 'GBd'), ('Her', 'Hēr'), ('HKR', 'HKR'), ('HN', 'HN'), ('IndBd', 'IndBd'), ('KAP', 'KAP'), ('MFRH', 'MFRH'), ('MHD', 'MHD'), ('MK_Andarz', 'MK-Andarz'), ('MYFr', 'MYFr'), ('N', 'N'), ('NM', 'NM'), ('OHD', 'OHD'), ('P', 'P'), ('PahlRivDd', 'PahlRivDd'), ('PT', 'PT'), ('PV', 'PV'), ('PY', 'PY'), ('RAF', 'RAF'), ('REA', 'RĒA'), ('SGW', 'ŠGW'), ('SiE', 'ŠiĒ'), ('SnS', 'ŠnŠ'), ('Vr', 'Vr'), ('Vyt', 'Vyt'), ('WCNA', 'WCNA'), ('WD', 'WD'), ('WDWM', 'WDWM'), ('WZ', 'WZ'), ('XD', 'X&D'), ('XAv', 'XAv'), ('ZFJ', 'ZFJ'), ('ZWY', 'ZWY')], max_length=10, unique=True)),
                ('genre', models.CharField(choices=[('ZAN', 'Zand'), ('PTE', 'PT-epitomes'), ('PTR', 'PT-reworking'), ('TEO', 'theological'), ('AUT', 'authorial-th'), ('JUR', 'jur'), ('AND', 'andarz'), ('NAR', 'narrative')], max_length=3, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='textsigle',
            constraint=models.CheckConstraint(check=models.Q(sigle__in=['AM', 'AOD', 'Aog', 'ASS', 'AWM', 'AWN', 'AZ', 'CHP', 'DA', 'Dd', 'Dk3', 'Dk4', 'Dk5', 'Dk6', 'Dk7', 'Dk8', 'Dk9', 'DkC', 'DMX', 'ENN', 'GA', 'GBd', 'Her', 'HKR', 'HN', 'IndBd', 'KAP', 'MFRH', 'MHD', 'MK_Andarz', 'MYFr', 'N', 'NM', 'OHD', 'P', 'PahlRivDd', 'PT', 'PV', 'PY', 'RAF', 'REA', 'SGW', 'SiE', 'SnS', 'Vr', 'Vyt', 'WCNA', 'WD', 'WDWM', 'WZ', 'XD', 'XAv', 'ZFJ', 'ZWY']), name='valid_sigle'),
        ),
        migrations.AddConstraint(
            model_name='textsigle',
            constraint=models.CheckConstraint(check=models.Q(genre__in=['ZAN', 'PTE', 'PTR', 'TEO', 'AUT', 'JUR', 'AND', 'NAR']), name='valid_genre'),
        ),
        migrations.AddConstraint(
            model_name='textsigle',
            constraint=models.UniqueConstraint(fields=('sigle', 'genre'), name='sigle_genre'),
        ),
        migrations.AlterField(
            model_name='historicaltext',
            name='text_sigle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='codex.textsigle'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_sigle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.textsigle'),
        ),
    ]
