# Generated by Django 3.1.13 on 2021-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_auto_20210902_1014'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='feature_name',
        ),
        migrations.RemoveConstraint(
            model_name='featurevalue',
            name='featurevalue_name',
        ),
        migrations.RemoveConstraint(
            model_name='morphologicalannotation',
            name='pos_feature_feature_value',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('name',), name='feature'),
        ),
        migrations.AddConstraint(
            model_name='featurevalue',
            constraint=models.UniqueConstraint(fields=('name',), name='featurevalue'),
        ),
        migrations.AddConstraint(
            model_name='morphologicalannotation',
            constraint=models.UniqueConstraint(fields=('feature', 'feature_value'), name='feature_feature_value'),
        ),
    ]
