# Generated by Django 3.1.13 on 2021-08-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_auto_20210827_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
