# Generated by Django 3.1.13 on 2021-09-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_auto_20210915_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='featurevalue',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='feature',
            name='feature',
        ),
        migrations.RemoveConstraint(
            model_name='featurevalue',
            name='featurevalue',
        ),
    ]
