# Generated by Django 3.1.13 on 2021-09-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_auto_20210901_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.feature'),
        ),
        migrations.AlterField(
            model_name='morphologicalannotation',
            name='feature_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.featurevalue'),
        ),
    ]
