# Generated by Django 3.1.13 on 2021-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0004_auto_20210902_1020'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='morphologicalannotation',
            name='valid_pos',
        ),
        migrations.RemoveConstraint(
            model_name='morphologicalannotation',
            name='feature_feature_value',
        ),
        migrations.RenameField(
            model_name='historicaltoken',
            old_name='morph_annotations',
            new_name='features',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='morph_annotations',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='morphologicalannotation',
            name='pos',
        ),
        migrations.AddField(
            model_name='historicaltoken',
            name='pos',
            field=models.CharField(choices=[('ADJ', 'ADJ'), ('ADP', 'ADP'), ('ADV', 'ADV'), ('AUX', 'AUX'), ('CCONJ', 'CCONJ'), ('DET', 'DET'), ('INTJ', 'INTJ'), ('NOUN', 'NOUN'), ('NUM', 'NUM'), ('PART', 'PART'), ('PRON', 'PRON'), ('PROPN', 'PROPN'), ('PUNCT', 'PUNCT'), ('SCONJO', 'SCONJO'), ('SYM', 'SYM'), ('VERB', 'VERB'), ('X', 'X')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='pos',
            field=models.CharField(choices=[('ADJ', 'ADJ'), ('ADP', 'ADP'), ('ADV', 'ADV'), ('AUX', 'AUX'), ('CCONJ', 'CCONJ'), ('DET', 'DET'), ('INTJ', 'INTJ'), ('NOUN', 'NOUN'), ('NUM', 'NUM'), ('PART', 'PART'), ('PRON', 'PRON'), ('PROPN', 'PROPN'), ('PUNCT', 'PUNCT'), ('SCONJO', 'SCONJO'), ('SYM', 'SYM'), ('VERB', 'VERB'), ('X', 'X')], max_length=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='morphologicalannotation',
            constraint=models.UniqueConstraint(fields=('feature', 'feature_value'), name='feature_featurevalue'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.CheckConstraint(check=models.Q(pos__in=['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJO', 'SYM', 'VERB', 'X']), name='valid_pos'),
        ),
    ]
