# Generated by Django 3.1.13 on 2021-09-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0005_auto_20210902_1028'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feature',
            name='feature',
        ),
    ]
