# Generated by Django 3.1.13 on 2021-09-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0006_auto_20210902_1043'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='morphologicalannotation',
            name='feature_featurevalue',
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('name',), name='feature'),
        ),
    ]
