# Generated by Django 3.1.13 on 2021-09-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0007_auto_20210902_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoken',
            name='features',
        ),
        migrations.RemoveField(
            model_name='token',
            name='features',
        ),
        migrations.AddField(
            model_name='token',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, to='codex.MorphologicalAnnotation'),
        ),
        migrations.AddConstraint(
            model_name='morphologicalannotation',
            constraint=models.UniqueConstraint(fields=('feature', 'feature_value'), name='feature_featurevalue'),
        ),
    ]
