# Generated by Django 3.1.13 on 2021-09-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_historicaldictionary_historicalentry'),
        ('codex', '0008_auto_20210902_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(choices=[('ADJ', 'ADJ'), ('ADP', 'ADP'), ('ADV', 'ADV'), ('AUX', 'AUX'), ('CCONJ', 'CCONJ'), ('DET', 'DET'), ('INTJ', 'INTJ'), ('NOUN', 'NOUN'), ('NUM', 'NUM'), ('PART', 'PART'), ('PRON', 'PRON'), ('PROPN', 'PROPN'), ('PUNCT', 'PUNCT'), ('SCONJO', 'SCONJO'), ('SYM', 'SYM'), ('VERB', 'VERB'), ('X', 'X')], max_length=6)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='token',
            name='valid_pos',
        ),
        migrations.AlterField(
            model_name='token',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dict.entry'),
        ),
        migrations.AddConstraint(
            model_name='pos',
            constraint=models.CheckConstraint(check=models.Q(pos__in=['ADJ', 'ADP', 'ADV', 'AUX', 'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT', 'SCONJO', 'SYM', 'VERB', 'X']), name='valid_pos'),
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='pos',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='codex.pos'),
        ),
        migrations.AlterField(
            model_name='token',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='codex.pos'),
        ),
    ]
