# Generated by Django 3.1.13 on 2021-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0010_auto_20210902_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsentence',
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='historicalverse',
            name='tokens',
        ),
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsection',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltext',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='tokens',
        ),
        migrations.AddField(
            model_name='sentence',
            name='tokens',
            field=models.ManyToManyField(to='codex.Token'),
        ),
        migrations.RemoveField(
            model_name='verse',
            name='tokens',
        ),
        migrations.AddField(
            model_name='verse',
            name='tokens',
            field=models.ManyToManyField(to='codex.Token'),
        ),
    ]
