# Generated by Django 3.1.13 on 2021-09-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0011_auto_20210902_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='token',
            name='token',
        ),
        migrations.AlterField(
            model_name='historicaltoken',
            name='trascription',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='line',
            name='side_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='codex.side'),
        ),
        migrations.AlterField(
            model_name='token',
            name='trascription',
            field=models.CharField(max_length=50),
        ),
    ]
