# Generated by Django 3.1.13 on 2021-09-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0013_auto_20210902_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='codextoken',
            name='line_position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
