# Generated by Django 3.1.13 on 2021-09-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0016_historicalcodextoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenSemantics',
        ),
    ]
