# Generated by Django 3.1.13 on 2021-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0017_delete_tokensemantics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='tokens',
            field=models.ManyToManyField(to='codex.CodexToken'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='tokens',
            field=models.ManyToManyField(to='codex.CodexToken'),
        ),
    ]
