# Generated by Django 4.1.4 on 2023-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmeaning',
            name='dictionary_meaning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meaning',
            name='dictionary_meaning',
            field=models.BooleanField(default=True),
        ),
    ]
