# Generated by Django 4.1.4 on 2023-02-21 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMeaning',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('meaning', models.TextField(blank=True, db_index=True, null=True)),
                ('language', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical meaning',
                'verbose_name_plural': 'historical meanings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='lemma1',
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='lemma2',
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='lemmameaning',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lemmameaning',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lemmameaning',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lemmameaning',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='lemmarelation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lemmarelation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lemmarelation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lemmarelation',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='historicallemma',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicallemma',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsemantic',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalsemantic',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lemma_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lemma_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meaning_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meaning_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semantic',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='semantic',
            name='updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalLemmaMeaning',
        ),
        migrations.DeleteModel(
            name='HistoricalLemmaRelation',
        ),
    ]
