# Generated by Django 4.1.4 on 2023-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallemma',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicallemma',
            name='word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalmeaning',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmeaning',
            name='meaning',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='word',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meaning',
            name='meaning',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
