# Generated by Django 4.1.4 on 2023-02-21 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0002_historicalmeaning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallemma',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicallemma',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicallemma',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicallemma',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalmeaning',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalmeaning',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalmeaning',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalmeaning',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalsemantic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalsemantic',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='semantic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='semantic',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='HistoricalLemmaRelation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('relation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lemma1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.lemma')),
                ('lemma2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.lemma')),
            ],
            options={
                'verbose_name': 'historical lemma relation',
                'verbose_name_plural': 'historical lemma relations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLemmaMeaning',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lemma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.lemma')),
                ('meaning', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.meaning')),
            ],
            options={
                'verbose_name': 'historical lemma meaning',
                'verbose_name_plural': 'historical lemma meanings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
