# Generated by Django 4.1.4 on 2023-05-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_historicallemma_category_lemma_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallemma',
            name='category',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='lemma',
            name='category',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
