# Generated by Django 4.2.2 on 2023-10-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_historicallemma_stage_historicalmeaning_stage_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lemmameaning',
            name='dict_lemmam_lemma_i_a920c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='lemmarelation',
            name='dict_lemmar_lemma1__ca4285_idx',
        ),
    ]
