# Generated by Django 4.2.2 on 2023-10-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_remove_lemmameaning_dict_lemmam_lemma_i_a920c1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lemma',
            name='dict_lemma_word_ac16a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='meaning',
            name='dict_meanin_meaning_01da8f_idx',
        ),
    ]
