# Generated by Django 4.2.7 on 2023-11-06 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models

def migrate_lemma_meaning_to_lemma_sense(apps, schema_editor):
    LemmaMeaning = apps.get_model('dict', 'LemmaMeaning')
    LemmaSense = apps.get_model('dict', 'LemmaSense')
    Sense = apps.get_model('dict', 'Sense')

    for lemma_meaning in LemmaMeaning.objects.all():
        # Use the 'id' from the related Meaning to find the corresponding Sense
        # Since you've already created a Sense with the same 'id' as the Meaning it came from,
        # you can directly use it to create the new LemmaSense instances.
        sense_instance = Sense.objects.get(id=lemma_meaning.meaning_id)  # 'meaning_id' is the FK to Meaning in LemmaMeaning

        # Now create the LemmaSense with this Sense instance and the Lemma from LemmaMeaning
        LemmaSense.objects.create(
            lemma=lemma_meaning.lemma,
            sense=sense_instance
        )

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0010_sense_historicalsense_sense_sense_language_sense'),
    ]

    operations = [
        migrations.CreateModel(
            name='LemmaSense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_lemma_sense', to='dict.lemma')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sense', to='dict.sense')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLemmaSense',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lemma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.lemma')),
                ('sense', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dict.sense')),
            ],
            options={
                'verbose_name': 'historical lemma sense',
                'verbose_name_plural': 'historical lemma senses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='lemmasense',
            constraint=models.UniqueConstraint(fields=('lemma', 'sense'), name='lemma_sense'),
        ),
        migrations.RunPython(migrate_lemma_meaning_to_lemma_sense),
    ]
