# Generated by Django 4.2.7 on 2024-02-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0013_remove_historicalmeaning_history_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsense',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sense',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
