# Generated by Django 4.2.7 on 2024-02-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0014_alter_historicalsense_language_alter_sense_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallemma',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='lemma1',
        ),
        migrations.RemoveField(
            model_name='historicallemmarelation',
            name='lemma2',
        ),
        migrations.RemoveField(
            model_name='historicallemmasense',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallemmasense',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='historicallemmasense',
            name='sense',
        ),
        migrations.RemoveField(
            model_name='historicalsemantic',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsense',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltermtech',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalDictionary',
        ),
        migrations.DeleteModel(
            name='HistoricalLemma',
        ),
        migrations.DeleteModel(
            name='HistoricalLemmaRelation',
        ),
        migrations.DeleteModel(
            name='HistoricalLemmaSense',
        ),
        migrations.DeleteModel(
            name='HistoricalSemantic',
        ),
        migrations.DeleteModel(
            name='HistoricalSense',
        ),
        migrations.DeleteModel(
            name='HistoricalTermTech',
        ),
    ]
