# Generated by Django 4.2.7 on 2024-03-14 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dict', '0016_lemma_created_by_lemma_modified_at_sense_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemma',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_lemmas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sense',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_senses', to=settings.AUTH_USER_MODEL),
        ),
    ]
