#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Now it's safe to collect static files
python /app/manage.py compilemessages
python /app/manage.py collectstatic --noinput

# Continue with the rest of the startup process
python /app/manage.py migrate
uvicorn config.asgi:application --host 0.0.0.0 --port 5000
