#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py tailwind install
python /app/manage.py tailwind build
python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

uvicorn config.asgi:application --host 0.0.0.0 --port 5000 