# Generated by Django 4.1.4 on 2023-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimage',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
