# Generated by Django 4.1.4 on 2023-02-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='identifier_source_number',
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('identifier', 'source'), name='identifier_source'),
        ),
    ]
