# Generated by Django 4.1.4 on 2023-02-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_identifier_source_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='identifier_source',
        ),
        migrations.AlterField(
            model_name='historicalimage',
            name='identifier',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
