# Generated by Django 4.1.4 on 2023-02-21 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_historicalimage_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalimage',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalimagesection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalimagesection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalimagesection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalimagesection',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='imagesection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='imagesection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='imagesection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='imagesection',
            name='updated_by',
        ),
    ]
