# Generated by Django 4.1.4 on 2023-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_image_identifier_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalimage',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('source', 'identifier'), name='image_source_identifier'),
        ),
    ]
