# Generated by Django 4.2.7 on 2024-02-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalimagesection',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalimagesection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalimagesection',
            name='section',
        ),
        migrations.DeleteModel(
            name='HistoricalImage',
        ),
        migrations.DeleteModel(
            name='HistoricalImageSection',
        ),
    ]
