# Generated by Django 4.2.7 on 2024-03-14 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0006_image_created_by_image_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
